### ISSUE TITLE
Snaz 1.10.0.8 Window stays minimized - can't open up the app

### ISSUE THREAD

**Issue by THELASTEXILE11** [JimmyAppelt/Snaz#10]
Hey there,

I am having some serious issues with this version of Snaz on my windows 10 desktop computer. I can't seem to do anything with the program once i have opened it. When i click my shortcuts to run Snaz, my computer acts as if it is already open but i do not get the usual x-window with all the controls. I figured that this was because it was minimized in my task bar tray but when i go down to click on the small icon for it, it just disappears and closes itself. I have tried giving the program admin rights as well as opening and closing the program in numerous ways, shut it down with task manager, and still i get nothing. I also tried going back to 10.0.7 and the issue still persist. Any ideas? If you need more details or have questions please ask! I love this program and want to get it up and running!

**Comment by JimmyAppelt** [comment]
Hi @THELASTEXILE11 

Checkout issue #8 

To fix this bug you need to perform a fresh installation that involves 3 simple steps.

You can read the necessary steps to have a clean installation [here](https://github.com/JimmyAppelt/Snaz/wiki/How-to-perform-a-fresh-installation)

**Comment by THELASTEXILE11** [comment]
Hey Jimmy,

Thanks so much for the help, worked like a charm! Was not aware of the other post someone else made, i am new to GitHub. Thanks for the fast response and keep up the good work, snaz makes my stream 10x's better!

**Comment by JimmyAppelt** [comment]
No problem @THELASTEXILE11 and you're welcome :smile: 

I'l let this issue open for some time, so people will find it easily.

**Comment by JimmyAppelt** [comment]
>As of 1.11.1.1 a re-install is not necessary anymore (just re-installing version 1.11.1.1 or above will fix this issue automatically)
