### ISSUE TITLE
Separated song info files

### ISSUE THREAD

**Issue by redion1992** [JimmyAppelt/Snaz#100]
Just wondering if it's possible to echo each of the Artist, Song, Album strings to their own file. This would allow different fonts, sizes, etc. for different data points.

eg.

`track-title.txt
track-artist.txt
track-album.txt`

**Comment by kcmartz** [comment]
(mobile ATM) this sounds like a good idea. I support and will mark it when I get home.

**Comment by JimmyAppelt** [comment]
Will be available from 1.12.3.2
