### ISSUE TITLE
Request: max letter output in 'Playing Now'

### ISSUE THREAD

**Issue by tenzai23** [JimmyAppelt/Snaz#102]
Yeah, basically what the title says, it's really hard to crop an txt file which changes it size all the time in OBS. Having a set amount of letters outputting would help alot doing that! Thanks in advance

**Comment by JimmyAppelt** [comment]
If i understand you're request correctly something like this will do the job ...
![2248b279688d247a3b86b1100b4d3e42](https://cloud.githubusercontent.com/assets/5420393/18595901/02a47e34-7c47-11e6-84bb-2557ef193b7a.png)

**Comment by kcmartz** [comment]
I approve of this. (on mobile so I can't vote on it yet)

**Comment by JimmyAppelt** [comment]
Will be available in 1.12.3.2
