### ISSUE TITLE
Non-square covers don't appear in Track Info

### ISSUE THREAD

**Issue by TheFireRed** [JimmyAppelt/Snaz#104]
As the title states, covers with different width/height don't seem to appear in Track Info, thus rendering blank pictures in the picture export.

![square](https://cloud.githubusercontent.com/assets/9060830/18771349/88d45a50-813e-11e6-8cad-215a83531bba.PNG)
![non square](https://cloud.githubusercontent.com/assets/9060830/18771350/88dd34d6-813e-11e6-8b20-0f5aaff45917.PNG)

**Comment by jcolsen** [comment]
If I'm not mistaken, album art is not being pulled from the music file itself, but from Spotify. It may simply not have found your song on Spotify.

**Comment by TheFireRed** [comment]
Oooh. That makes sense. I thought otherwise.

**Comment by kcmartz** [comment]
Just a tip, but if you embed the art through iTunes, it should work better and iTunes uses art in that application.

**Comment by JimmyAppelt** [comment]
Yes correct, album and album art are both from the Spotify database for all players except for iTunes

You can read player specific things [here](https://github.com/JimmyAppelt/Snaz/wiki/Playing-Now)

In case you have any other issue's feel free to re-open a ticket.
