### ISSUE TITLE
Encoding output file

### ISSUE THREAD

**Issue by webadequate** [JimmyAppelt/Snaz#106]
Hello.
Snaz save output file (current song) in utf-8 with BOM. How can compel it save without BOM?

**Comment by JimmyAppelt** [comment]
hi @webadequate,

Would you mind giving me a heads-up on why you would need the file without BOM *(byte order mark)* ?

**Comment by webadequate** [comment]
First of all, it not include in ASCII symbols. Therefore, any native systems will not  support that. The second, the most programs doesn't support BOM and can be crashed. For example, in PHP any BOM file throw up error in any POST request (famous error of "headers by sent"). Because of it, all JetBrains products recommend remove BOM from any file and doesn't mark it by default.

**Comment by JimmyAppelt** [comment]
Ok, sure i will dig into it ... will release an update soon, will try to get this in for ya

**Comment by webadequate** [comment]
In particular, I have a problem with LUA scripting. I try to read your output file, and I get encoding error. LUA natively work with clear ASCII and BOM mark gives error encoding.

**Comment by JimmyAppelt** [comment]
Yeah understand the issue you might encounter ... will look into it

**Comment by JimmyAppelt** [comment]
Please also not that text files are written in UTF-8 not ASCII *(since most stream software programs only support UTF-8)*

The text files will be written without BOM from next milestone
