### ISSUE TITLE
$h in Time only outputs one zero

### ISSUE THREAD

**Issue by Ragowit** [JimmyAppelt/Snaz#109]
At the time of this writing so is it 00:48 at my place. However, Snaz output $h:$m as 0:48

**Comment by Ragowit** [comment]
Never mind, found it was a setting that removed leading zeroes from hours.

**Comment by JimmyAppelt** [comment]
Indeed :)

![972215a828a3eae90bffec81bc7101e9](https://cloud.githubusercontent.com/assets/5420393/18975091/f8edccc2-86a7-11e6-9f15-3cc88e4926e9.png)
