### ISSUE TITLE
Count not initialize the network traffic counter

### ISSUE THREAD

**Issue by mrworm1** [JimmyAppelt/Snaz#11]
Snaz Verion 1.10.0.8 
Windows 10

I've searched for previous mentions of this issue and found it one mentioned but no resolutions.
https://obsproject.com/forum/threads/snaz.18587/page-16

I've followed the reinstall guide several times but have had the consistent problem of two error prompts. "Count not initialize the network traffic counter", Cannot Load Counter Name data because an invalid index" was read from the registry.

Any assistance would be very much appreciated.

Thank you.

**Comment by JimmyAppelt** [comment]
hi @mrworm1 

Could you try and check if your performance counters are not corrupted. Let us rebuild it to test.

* Close all running programs
* Open a command prompt (with Admin privileges)
* run command: `lodctr /R`

A message with: `Info: Successfully rebuilt performance counter seting ...` will appear on succes.

Then re-open Snaz and check if the Warning still appears.

**Comment by mrworm1** [comment]
Unable to rebuild performance counter setting from system backup store, error code is 2

**Comment by mrworm1** [comment]
I followed the following solution to rebuild the perfcounter.  Issue is resolved.

https://social.technet.microsoft.com/forums/windows/en-us/9b01e1a6-d872-4f28-9280-f35d6ca02a9f/lodctr-r-error-code-2?forum=w7itprogeneral


Thank you for your assistance.  =)

**Comment by JimmyAppelt** [comment]
Great, have a nice day @mrworm1 :+1:

**Comment by JimmyAppelt** [comment]
The solution (in this case) is added to the wiki [here](https://github.com/JimmyAppelt/Snaz/wiki/System-info) under "Solving warning or error"
