### ISSUE TITLE
Avast stating 1.12.4.1 has a virus

### ISSUE THREAD

**Issue by gamerscircle** [JimmyAppelt/Snaz#110]
I know this is most likely an Avast issue, but I thought that I would report it to raise some possible awareness?

**Comment by JimmyAppelt** [comment]
Hi,

Could you tell me what Avast reports ?

**Comment by JimmyAppelt** [comment]
Anyway i submitted a false positive to avast for this, hope it helps. (Nut sure in what degree that will work in the future)

![68df81dd03dcc281d30963f0939cedca](https://cloud.githubusercontent.com/assets/5420393/19563202/796e32be-96df-11e6-9619-da7f3e8c16c0.png)

**Comment by EdjeGaming** [comment]
Done. 
I hope it helps. 
![snaz-report](https://cloud.githubusercontent.com/assets/22682140/19572618/4f401b82-9703-11e6-8757-a505584af6fa.png)

**Comment by JimmyAppelt** [comment]
From the Avast customer care,

> Seems the issue is no more present.
>If you need further assistance, don't hesitate to contact me again.

**Comment by gamerscircle** [comment]
I was able to download 1.12.4.1 and didn’t get an message from Avast, thank you.
