### ISSUE TITLE
Playing Now (Spotify) does not show album art or album name.

### ISSUE THREAD

**Issue by enzanki-ars** [JimmyAppelt/Snaz#111]
![image](https://cloud.githubusercontent.com/assets/8580211/19629773/f8b56e2c-9949-11e6-8350-c051aa7d351c.png)

![image](https://cloud.githubusercontent.com/assets/8580211/19629787/35376fd0-994a-11e6-999d-7cad4016bbd6.png)

I reloaded both Spotify and Snaz, but I am still seeing this. It does work with some other songs though, but not this one.

**Comment by enzanki-ars** [comment]
Saw this on the wiki: `Album and album art are query-ed from a database (will respond with the first match, if any) for all players except iTunes`

What database is Snaz using.  I could check if this is in the database.

**Comment by JimmyAppelt** [comment]
@enzanki-ars  i see the song is `0_7-waitfortheQ.ogg` instead of `1.0_7-waitfortheQ.ogg`

This must have to do with the algorithm i wrote to collect the data.

**Comment by enzanki-ars** [comment]
Oh.  I didn't even notice that the title was incorrect.

**Comment by JimmyAppelt** [comment]
If the title will be correct the album will come ... 

I'l investigate this ...

**Comment by JimmyAppelt** [comment]
Should be fixed in 1.12.4.2 (it's already live so closing Snaz and reopen it will fire an update)

**Comment by enzanki-ars** [comment]
That fixed it.  Thanks!
