### ISSUE TITLE
Album art not working with ITunes "Radio" and "For You" 12.5.1.21?

### ISSUE THREAD

**Issue by argash** [JimmyAppelt/Snaz#112]
Track names pull fine, just not album art.

**Comment by JimmyAppelt** [comment]
@argash is this on a specific album or song ?

I have  iTunes 12.5.1.21 installed and working smoothly.

**Comment by argash** [comment]
I've tried multiple radio stations and "For you" playlists, still need to try some local content.

**Comment by JimmyAppelt** [comment]
Oh, right ... not sure with `radio` and `for you` stations. I'm only able to support/test local files since I do not own a *Apple Music* subscription.

**Comment by JimmyAppelt** [comment]
That is kind of you @argash , sadly i have to test players often, being able to test this once will not be sufficient. Testing needs to happen regularly.

As Snaz is freeware and a project that i keep up to date in my free time, there is no real reason for me to support payed (departments of) players.

**Comment by JimmyAppelt** [comment]
Will close this issue for now, since this is not really a bug. 
In case you have other issue's, feel free to answer this ticket of to re-open another one.
