### ISSUE TITLE
Doesn't launch

### ISSUE THREAD

**Issue by alhassanv** [JimmyAppelt/Snaz#116]
Hey, 
When i try opening the program nothing happens please fix it.
Nothing shows up!
Any suggestions??

**Comment by JimmyAppelt** [comment]
Does this occurs right after installation ? 
Snaz opened fine before ?

**Comment by alhassanv** [comment]
it is fixed

**Comment by alhassanv** [comment]
-- Please reply above this line --

Hello Jimmyappelt/snaz,

We got your help request! One of our agents will respond to you as
soon as possible.

Thanks!

-----------------------------------------------------------
## Jimmyappelt/snaz sent a message, on Nov 3 @ 9:49pm (UTC):



	Closed #116 [1]. 

	-
 You are receiving this because you authored the thread.
 Reply to this email directly, view it on GitHub [2], or mute the
thread [3].

Links:
------
[1] https://github.com/JimmyAppelt/Snaz/issues/116
[2] https://github.com/JimmyAppelt/Snaz/issues/116#event-847137600
[3]
