### ISSUE TITLE
Add a Random Text Generator 

### ISSUE THREAD

**Issue by MontageZz** [JimmyAppelt/Snaz#118]
allow the program to ask the user how many things they would like to randomize then allow the user to enter the thing to me randomized and send the randomized text to a txt file

**Comment by JimmyAppelt** [comment]
hi @MontageZz 

I'm not entirely convinced this is a feature for Snaz.

You can randomize text lines easily on some online tool like [textmechanic](http://textmechanic.com/text-tools/basic-text-tools/sort-text-lines/)
