### ISSUE TITLE
[Suggestion] Able to run with OBS Studio

### ISSUE THREAD

**Issue by Awesomeest1234** [JimmyAppelt/Snaz#119]
I tried to use snaz with [OBS Studio](https://obsproject.com/download) and it does not work it only works with [OBS Classic](https://obsproject.com/download)

**Comment by JimmyAppelt** [comment]
Verify that you did made the correct steps [here](https://github.com/JimmyAppelt/Snaz/wiki/OBS) for OBS Studio
