### ISSUE TITLE
Any plans to expand the Now Playing section?

### ISSUE THREAD

**Issue by MatthewLyonAnimations** [JimmyAppelt/Snaz#12]
Are there plans to add more media players to the "Now Playing" section in the future, such as Winamp or VLC?

**Comment by JimmyAppelt** [comment]
HI @MatthewLyonAnimations,

I designed the `Now Playing` feature to be able to add more players in the future. Adding more players and so depends on the generosity of donations of coarse.

I'm not to sure about implementing VLC ? It's more of a video player i take.

**Comment by JimmyAppelt** [comment]
I take this is an answer to your question.

If i receive the necessary support i will definitely integrate Winamp.

If you have any other question, feel free to open a new issue.

**Comment by Slegnor** [comment]
I know this is closed but I was about to request the same support for Winamp

**Comment by JimmyAppelt** [comment]
@Slegnor thank you, your request is noted

**Comment by JimmyAppelt** [comment]
I have `Winamp` coded, but for the best will, some user better beta test.

Join Discord (link is in the Help menu of snaz) to get a Beta when it is ready.

**Comment by JimmyAppelt** [comment]
@Slegnor  @MatthewLyonAnimations 

I have Winamp coded, but for the best will, some user better beta test.

Join Discord (link is in the Help menu of snaz) to get a Beta when it is ready.
