### ISSUE TITLE
Add seconds subdivision with $u up to milliseconds to Countdown/Chronos

### ISSUE THREAD

**Issue by e7d** [JimmyAppelt/Snaz#120]
Useful when you want to do a short countdown, looking more active on screen than just the seconds counting. Maybe should be able to understand $u for 2 digits, and $uu for three digits.

Samples :
`$m:$s:$u` for `07:43:25`
`$m:$s:$uu` for `07:43:253`

**Comment by JimmyAppelt** [comment]
This has bin asked before, sadly the time to write milliseconds and the time for stream software to read the file takes to much time.

So essentially this is not something that is going to work properly.
