### ISSUE TITLE
Now playing XML Files constantly reformatting

### ISSUE THREAD

**Issue by Sinfuldeity** [JimmyAppelt/Snaz#122]
Hey Jim, ive been noticing lately that after restarting my computer on the Windows 10 AU, all of my XML files will reformat and have to be regenerated by snaz. It's not too much of an inconvenience to reset the files and format them the way I want them to be setup, but thought I'd let you know about the issue! Here is the message I get upon a fresh start! 
![image](https://cloud.githubusercontent.com/assets/23106082/20467227/1105fef2-af51-11e6-8257-ec9f4ab81810.png)

**Comment by JimmyAppelt** [comment]
@Sinfuldeity hi there,

This is a error message from the `Text line changer` , it means that the file contents of the *TextLines.xml* are not correctly formatted. 

To see what going on we need to check your file contents.

So ...

 * Open Snaz
 * Click yes on the error
 * Close Snaz
 * Open op the `TextLines.xml file manually with *Notepad*
 * Post the content here so I can study it

**Comment by Sinfuldeity** [comment]
<?xml version="1.0" encoding="utf-8"?>

<TextLines>
  <Line Active="True" Random="True" String="Line holder 1" />
  <Line Active="True" Random="True" String="Line holder 2" />
  <Line Active="True" Random="True" String="Line holder 3" />
  <Line Active="True" Random="True" String="Line holder 4" />
  <Line Active="True" Random="True" String="Line holder 5" />
</TextLines>


Exact content above.

**Comment by Sinfuldeity** [comment]
exact content should be below 
<?xml version="1.0" encoding="utf-8"?>

<TextLines>
  <Line Active="True" Random="True" String="Line holder 1" />
  <Line Active="True" Random="True" String="Line holder 2" />
  <Line Active="True" Random="True" String="Line holder 3" />
  <Line Active="True" Random="True" String="Line holder 4" />
  <Line Active="True" Random="True" String="Line holder 5" />
</TextLines>

**Comment by JimmyAppelt** [comment]
Content received trough discord:

```xml
<?xml version="1.0" encoding="utf-8"?>
<!--This file is generated by Snaz, u can make changes to this file, but keep the XML structure intact-->
<TextLines>
  <Line Active="True" Random="True" String="Line holder 1" />
  <Line Active="True" Random="True" String="Line holder 2" />
  <Line Active="True" Random="True" String="Line holder 3" />
  <Line Active="True" Random="True" String="Line holder 4" />
  <Line Active="True" Random="True" String="Line holder 5" />
</TextLines>
```

**Comment by JimmyAppelt** [comment]
After a conversation trough discord, this issue seems to be exist locally only and can't be addressed as a bug or issue to Snaz itself.
