### ISSUE TITLE
Death Counter

### ISSUE THREAD

**Issue by RetroSpective1981** [JimmyAppelt/Snaz#125]
Why not add a death counter?

**Comment by JimmyAppelt** [comment]
@RetroSpective1981 

This seams to be a duplicate request #32 😉

This request will now be referenced on the original, thanks for you're request.

Read follow FAQ on [how to upvote a request](https://github.com/JimmyAppelt/Snaz/wiki/FAQ#how-do-i-need-to-vote-for-a-request-thats-already-have-been-made).
