### ISSUE TITLE
Request - Add subscriber count

### ISSUE THREAD

**Issue by AndoidGameTips** [JimmyAppelt/Snaz#129]
Please add a subcounter! That would be so awesome!

**Comment by JimmyAppelt** [comment]
> Please add a subcounter

Could you be more specific ? 😃

**Comment by AndoidGameTips** [comment]
You have a view counter for twitch, but it would be nice if you can add a subscriber count tool!
Because I use your 'program' in my livestreams in obs studio! and a subcounter would be awesome

**Comment by AndoidGameTips** [comment]
I mean something like this: https://livecounts.net/channel/andoidgametips
But then in text format that automatically updates

**Comment by Awesomeest123yt** [comment]
I think that would be a great Idea @AndoidGameTips
