### ISSUE TITLE
Textline

### ISSUE THREAD

**Issue by atlasthegamer** [JimmyAppelt/Snaz#13]
I'm trying to create a list of scrolling facts about myself "Atlas Fact #1: Atlas likes greek..etc" but every time I click within the created lines area it brings up an error "Unhandled exception has occured in your application. If you click continue, the application will ignore this error and attempt to continue. If you click Quit, the application will close immediately.     Index-1 does not have a value." and it has a whole list of the error log which I can provide if necessary. I have never had any other problems with snaz, it's an amazing application and I really want to help you guys keep up the good work in any way I can so thank you so much for your consideration and just let me know if I'm bein dumb or if there's a way to fix it!

**Comment by JimmyAppelt** [comment]
hi @atlasthegamer,

I will fix asap !

**Comment by atlasthegamer** [comment]
Wow, I think you just set a record for fastest support time ever O.O Also I found that the text still works, but once it's there you can't edit it at all. That includes deleting it or moving them individually although you can randomize the lines and start the text-flow, hope that helps :)

**Comment by JimmyAppelt** [comment]
You should see a popup box where you can edit the text line again when double clicking it. I'l debug it 
and see whats going on :+1:

**Comment by atlasthegamer** [comment]
No rush man, keep up the good work :+1:

**Comment by JimmyAppelt** [comment]
I pushed 1.11.1.3 that should fix this issue, let me know if it is solved on your end.

(Close snaz and restart it will fire an update)

**Comment by atlasthegamer** [comment]
Ahhh you're a legend man, thank you so much!!!

**Comment by JimmyAppelt** [comment]
I take it is solved ? :smile:

**Comment by atlasthegamer** [comment]
Yes it solved I'm so sorry for not getting back to you, thank you so much
haha. I got caught up with the newly operable feature xD

**Comment by JimmyAppelt** [comment]
Great thing @atlasthegamer, have a nice day/evening :star2:
