### ISSUE TITLE
Problem with Foobar2000 capture

### ISSUE THREAD

**Issue by Yupppi** [JimmyAppelt/Snaz#131]
I was capturing song title from foobar2000. The file was in .flac format and everything seemed to be fine with ID other than that the song title had "#08 ]" at the start in Snaz. Attached pictures of foobar layout and snaz capture, I suppose it's a problem with .flac file ID. The file name is "08 Karma.flac". It worked just fine with another song in .mp3 with same file name format and foobar layout. Foobar version is 1.3.14.
![foobar layout](https://cloud.githubusercontent.com/assets/24705202/22379468/236a0e20-e4c2-11e6-952b-0c261eafed1c.JPG)
![snaz capture](https://cloud.githubusercontent.com/assets/24705202/22379470/264e192e-e4c2-11e6-9e0b-dbb65af48cba.JPG)

**Comment by JimmyAppelt** [comment]
Hi @Yupppi ,

In case you have and issue with the default window title notation, I suggest using the custom capture option, and correct the title notation inside foobar2000.

Details about this are here : https://github.com/JimmyAppelt/Snaz/wiki/Foobar2000

**Comment by Yupppi** [comment]
Thanks for the reply. I tweaked around a bit (took me a moment to understand the whole process) and came to a state where Snaz recognizes song title and artist backwards but otherwise it works. Basically it sets anything that isn't %artist% as artist and artist as song.

**Comment by JimmyAppelt** [comment]
No if, you use custom capture, you have to use the following notation (because of it's algorithm)

`%title% '♫' %artist% '♫' %track artist% '♫' %albumartist%`
