### ISSUE TITLE
Set Default Album Image

### ISSUE THREAD

**Issue by TheScientistPT** [JimmyAppelt/Snaz#132]
I would like a feature where I could add a custom image in case a certain track i'm playing does not have an album image.

**Comment by JimmyAppelt** [comment]
Indeed there is no option for that at the moment.

Al trough a backdoor is to use 2 images in your stream software on top of each other (with same dimensions, and the one from snaz album on top). That could do the trick for now.

**Comment by TheScientistPT** [comment]
Okay, thank you very much, and great work on the program!
