### ISSUE TITLE
Text is not displayed on the screen

### ISSUE THREAD

**Issue by frikiloko** [JimmyAppelt/Snaz#139]
I want to put a chrono up while recording a game.  I can see the chrono up in OBS in its window over the game, it's perfect but when I set fullscreen to play the chrono up is not shown. I tried text(GDI+) and obsolete text(free type2) without sucess. The game is set to capture game on OBS and capture specific window(the game.exe)

**Comment by JimmyAppelt** [comment]
Hi @frikiloko,

When the textfile is not shown, it' s probably something with OBS itself. Please double check your settings.

**Comment by JimmyAppelt** [comment]
Closed due inactivity (free to reply or open a new ticket in case you still face the issue)
