### ISSUE TITLE
When Now Playing sees an & in song name, and elgato shows sliding text, it loops indefinitely

### ISSUE THREAD

**Issue by AskaLangly** [JimmyAppelt/Snaz#140]
Used Spotify to test.
Played a song that has an ampersand (&) in its artist and song tags.
e.g. [Chase & Status - Lost & Not Found]
Using elgato's software.
Add text to overlay, choose 'Slide In Left'.
The text keeps sliding to no end.

**Comment by JimmyAppelt** [comment]
I would recommend to contact support at Elgato. Snaz only creates the text file itself ... it's up to the Elgato software to read/animate it.
