### ISSUE TITLE
Very slow and laggy GUI on a fresh install (approx. 1 frame in 6 seconds)

### ISSUE THREAD

**Issue by polyzium** [JimmyAppelt/Snaz#141]
As the title says. I use Windows 10 Pro 64 bit

**Comment by JimmyAppelt** [comment]
Do you get any errors ?
You have the latest version of Snaz 1.12.5.0 ?

I use exact same system specs ... running perfectly fine on my machine.

**Comment by polyzium** [comment]
@JimmyAppelt No i don't get any errors

**Comment by polyzium** [comment]
So how do i solve this problem?

**Comment by JimmyAppelt** [comment]
Since this is a machine specific issue, I can't say whats happening there. I would have to investigate that issue on that particular machine (since I'm unable to replicate that issue locally).

**Comment by polyzium** [comment]
Do you mean that this program is optimised for a particular CPU/hardware?

**Comment by JimmyAppelt** [comment]
Nope, I mean that issue is as far as I know only existing on your computer for one reason or another. :)

**Comment by polyzium** [comment]
Well in case if you need my system specs i use Core i3 3220 and a B75-based motherboard (yes it's 4 years old, i plan to upgrade soon)

**Comment by polyzium** [comment]
However it performs OK on my Windows tablet (Atom Z3735F)

**Comment by JimmyAppelt** [comment]
@polyzium could you try and check task manager when Snaz is open, to see how much CPU it's using ?

**Comment by polyzium** [comment]
**The problem was with polling send/receive rate indicators**, Jim will add that in the next release

**Comment by JimmyAppelt** [comment]
Setting implemented for 1.2.5.1

Small info added in the doc: 
https://github.com/JimmyAppelt/Snaz/wiki/Solving-warning-or-error-within-System-Info
