### ISSUE TITLE
Shortcuts for NOW PLAYING

### ISSUE THREAD

**Issue by FabiXD** [JimmyAppelt/Snaz#143]
I wanna stream and i think snaz is rly good app for stream. But what if i want to set the shortcuts for next/prev song or higher/lower volume? Should i use something in win10 settings or no? i won´t always switch to desktop to change the song manually by clicking on next/prev song. Any halp ?2?

**Comment by JimmyAppelt** [comment]
Snaz does currently not the option to have shortcuts for these actions. 
Is your music player not able to have shortcuts itself ?

**Comment by JimmyAppelt** [comment]
Closed due inactivity. (You can still reply to this ticket if you like)
