### ISSUE TITLE
Support other streaming sites

### ISSUE THREAD

**Issue by Paladinleeds** [JimmyAppelt/Snaz#144]
Allow a way to connect to other sites such as Hitbox and Beam. Perhaps even allowing more technical users to dig into the APIs themselves and pull up certain information needed to parse the data if their site is not officially supported.

**Comment by JimmyAppelt** [comment]
Dynamic files is the feature that will take care of this "for more technical users".

Some docs about DF can be found here https://github.com/JimmyAppelt/Snaz/wiki/Dynamic-Files
