### ISSUE TITLE
New Line

### ISSUE THREAD

**Issue by hhch0928** [JimmyAppelt/Snaz#146]
Can you make \n as a new line or anything else to replace it?

**Comment by JimmyAppelt** [comment]
> Can you make \n as a new line or anything else to replace it?

Where , what, how ? 😃

**Comment by hhch0928** [comment]
I mean make \n as a placeholder to make a new line in txt file....

**Comment by JimmyAppelt** [comment]
@hhch0928 could you specify in what textfile you would want this ?

**Comment by JimmyAppelt** [comment]
Closed due no feedback. Feel free to reply on this ticket or open a new one.
