### ISSUE TITLE
For mac livestreamers

### ISSUE THREAD

**Issue by ColonelPhoenix** [JimmyAppelt/Snaz#148]
hey man sorry for brining this up, but i'm currently learning live streaming and i'm about to do lifestream speed runs for retro games and i've been looking at snaz and it doesn't have a mac download, can you help me please? my mac is the only computer that has all retro games on it.

**Comment by JimmyAppelt** [comment]
Snaz is windows Only I'm affraid

**Comment by ColonelPhoenix** [comment]
well dang it, is there another way of getting the program without using wine? (tried it and it left my brain scratching)

**Comment by ColonelPhoenix** [comment]
or any other programs.

**Comment by JimmyAppelt** [comment]
You can try with Wine, but I never had any confirmation of someone that is able to get it running that way.

**Comment by ColonelPhoenix** [comment]
ok then, well thanks anyway
