### ISSUE TITLE
Simple AM and PM addition to the clock.

### ISSUE THREAD

**Issue by OutThnk** [JimmyAppelt/Snaz#149]
Looking for a simple am and pm addition to the clock.

**Comment by JimmyAppelt** [comment]
Does this help ? 

https://github.com/JimmyAppelt/Snaz/wiki/Time

**Comment by OutThnk** [comment]
Awesome, kind of a noob question it was. ;)  Thank you for being polite and helpful.

**Comment by JimmyAppelt** [comment]
You're welcome
