### ISSUE TITLE
Confirmation box on close or option to close to taskbar

### ISSUE THREAD

**Issue by shogan01** [JimmyAppelt/Snaz#15]
Have a confirmation to make sure Snaz does not get closed accidentally when hitting the X button, or have optional to set "close to taskbar" in options

**Comment by JimmyAppelt** [comment]
Hi @shogan01 ,

I will implement this request for you in a future update :+1:

**Comment by JimmyAppelt** [comment]
Implemented, will be available in next release :star2: 

Thanks for submitting this request.
