### ISSUE TITLE
Change default path for generated files (Request)

### ISSUE THREAD

**Issue by Megagamers98** [JimmyAppelt/Snaz#151]
It would be very usefull to be able to change the default directory where textFiles and images are saved 
This would make easy to users and other programs to acces the files 

Would like this for making a customizable browser source to show the information that snaz provides easily for everyone to use.

Thanks

**Comment by AcornBBCnut** [comment]
Yep, I'd like to see this feature too. I kjeep all my stream data files on a seperate, removable drive and it would be great to include this too.
