### ISSUE TITLE
Infinite popup windows when not connected to internet

### ISSUE THREAD

**Issue by Stick1000** [JimmyAppelt/Snaz#153]
When launched while not connected to the internet, Snaz displays popups every 1 second telling the same message. To stop the popups, a reconnection to the internet is required.

**Comment by JimmyAppelt** [comment]
And what does the irritating pop say ?

**Comment by JimmyAppelt** [comment]
Never mind I see what you mean 👍

**Comment by JimmyAppelt** [comment]
In case you really have a problem with it for now, you can disable the Network meter in `File > Settings> System Info`

**Comment by Stick1000** [comment]
Well, thanks for that.

**Comment by Stick1000** [comment]
Just updated. Yeah the bug is gone. Great job 👏
