### ISSUE TITLE
Sam Broadcaster?

### ISSUE THREAD

**Issue by OutThnk** [JimmyAppelt/Snaz#156]
As we approach the re-launch of our online radio station I am wondering about integrating this into my live video streams.  Do you have plans to ever make SamBroadcaster an option in the Playing Now section?  It works great with the options you currently have, and I thank you!  However, SamBroadcaster is our primary audio out for music when the station once again goes live.  Thank you, Michael aka OutThnk

**Comment by JimmyAppelt** [comment]
Hi @OutThnk,

First time I hear about SamBroadcaster, I'm sure it will be known by you guys as a great software. 

However Snaz itself is free software, the player you use is a paid software/service. I can not subscribe to it just to test it and make things work,  I have to test players on regularly bases. 

There are far not enough donations to do this kind of thing (I appreciate yours!) 

Kind regards
Jim

**Comment by OutThnk** [comment]
That is completely understandable.  Maybe, sometime in the future, I can supply you with a key to the software to do testing.  Thank you for the quick response.
