### ISSUE TITLE
Chrono - Count up time to exceed display of 60 min

### ISSUE THREAD

**Issue by alexfawaz** [JimmyAppelt/Snaz#157]
Hello, I am trying to use the app to be a game timer for some amateur soccer games I am going to stream. Is there a way to allow the timer to display minutes exceeding 60 without going to hour and minute format.  Soccer games run just about 90 min and usually displayed as total minutes counting up to 90. How can I achieve this.

**Comment by JimmyAppelt** [comment]
Hi @alexfawaz,

The format code you're looking for is `$totalminutes`

Documentation can be found here https://github.com/JimmyAppelt/Snaz/wiki/Chrono-Up
