### ISSUE TITLE
[Request] Amazon Music

### ISSUE THREAD

**Issue by BillieJackFu** [JimmyAppelt/Snaz#158]
Hey Jim,

So Amazon Prime members can use Amazon Music on their PCs so I was wondering if you could add a hook for Amazon Music Player in the Playing Now tab. 
[Amazon Music Player](https://music.amazon.com/gp/dmusic/desktop/downloadPlayer/ref=dm_mo_instruct_ch)

Thanks

BillieJackFu

**Comment by JimmyAppelt** [comment]
Hi @BillieJackFu ,

I'm sorry there are no plans to integrate this player

Kind regards
