### ISSUE TITLE
Playing Now - Stopped showing artwork

### ISSUE THREAD

**Issue by nabstarrrr** [JimmyAppelt/Snaz#159]
Everything was working fine until this weekend. I have deleted Snaz and redownloaded and still no artwork. I have restarted multiple time.

**Comment by Clinpachi** [comment]
Can confirm the same issue. I thought it was just me and proceeded to reinstall try various web tips as well to no avail.

**Comment by jcolsen** [comment]
There seems to be something changed at Spotify's end since other similar tools are experiencing the same issue. The developer is currently away for a few days, but will have a look at it once he returns. Sorry for any inconvenience in the meantime.

**Comment by Zillah7478** [comment]
May we have an ETA when this will be worked on? Thank you.

**Comment by mackenzie** [comment]
Just to complicate things, it's not just Spotify. Grabbing art from Winamp stopped working as well.

**Comment by jcolsen** [comment]
It's the same issue, but thanks for reporting it. With Snaz, album art is pulled from Spotify no matter which music player you're using. Again, the developer is currently away and will look into this when he returns. ETA 7-10 days.

**Comment by JimmyAppelt** [comment]
It seems that the Spotify API now requires to have authentication to receive these, which was not necessary before. Will look into it asap.

**Comment by JimmyAppelt** [comment]
Documentation: https://github.com/JimmyAppelt/Snaz/wiki/Spotify-API-credentials

**Comment by nabstarrrr** [comment]
Thank you so much for your help.
