### ISSUE TITLE
Chrono's hooking issue with OBS MP

### ISSUE THREAD

**Issue by shogan01** [JimmyAppelt/Snaz#16]
I am still testing something with the hooking of obs mp and the chronos
I have found a way to have it work with the proper output all the time if i open snaz first, run chrono then run OBS MP. 

If I open OBS MP first before opening snaz the incorrect output shows

**Comment by JimmyAppelt** [comment]
After a replication, i can confirm that this is a issue with OBS MP itself. Will investigate the nature of the problem and then report it to OBS.

**Comment by JimmyAppelt** [comment]
OBS MP 0.12.1 should close this issue (as it was OBS Client related)

> Fixed various bugs with the freetype2 text source where the text could show up as garbled or not display
