### ISSUE TITLE
Spotify stopped showing artwork PLZZ!! Help!!!

### ISSUE THREAD

**Issue by XxJoLaLegendexX** [JimmyAppelt/Snaz#160]
next time im have start Snaz and open Spotify and im check OBS, i see no Artwork of my music.. PLZZ FIXEE THAT SOON. (MAYBE WITH NEW UPDATE) THANKS!!!!

**Comment by jcolsen** [comment]
This is a know issue, please refer to: https://github.com/JimmyAppelt/Snaz/issues/159
