### ISSUE TITLE
[REQUEST] Multiple Text Line Changer

### ISSUE THREAD

**Issue by ElliottC99** [JimmyAppelt/Snaz#161]
For my stream, I would like to have multiple Text Line Changers in my stream. So I can have them running in sync on my screen all at once.

Is this possible to have, without install Snaz X amount of times?

If not, I'd really appreciate this feature being added.

**Comment by FatherlyArson** [comment]
this is what id love to have also

+1

**Comment by JimmyAppelt** [comment]
Hi, I'm sorry requests are closed currently closed.

Regards
