### ISSUE TITLE
Request - Double Digits for the Viewer Count

### ISSUE THREAD

**Issue by 6kbyte** [JimmyAppelt/Snaz#162]
Hi,

first I want to say thank you for this awesome tool Jimmy!!! I am completely new @GitHub and @Twitch and englisch is not my native language - so sorry if its bad.

Iam using the viewer-count (twitch viewers tab) for my twitch stream and the counter is embedded in a small overlay picture in the left upper corner (OBS). Mostly I have less then 10 viewers/only 1 digit and the counter fits perfectly/centered into my small overlay picture - in the past days i reached 10-20 simultaneously viewers and the counter added one more digit. Everytime that happens I have to readjust the counter overlay position because its not centered anymore. It really would help to have the double digits option in the counter too (like in the time tab) - can you made that possible?  

Regards,

6kbyte

**Comment by Giaco35** [comment]
That's a hell of a great idea! It would allow for better text aligning, GDI+ being the only text source on OBS that can center text and looking like shit... Freetype2 + Double digits would be awesome!

**Comment by JimmyAppelt** [comment]
How come it is not centered then ? Aren't there settings to center the text itself inside OBS ?
