### ISSUE TITLE
Now Playing Software Request

### ISSUE THREAD

**Issue by VirusZ333** [JimmyAppelt/Snaz#163]
Alot of streamers use Ankhbot as their bot including me. I would like to see if u are able to make Ahnkbot show the playlist on stream.

**Comment by JimmyAppelt** [comment]
>  I would like to see if u are able to make Ahnkbot show the playlist on stream.

I'm unsure why you ask this request here. Snaz does not requests or outputs playlists, and is not related in any way to Ahnkbot.
