### ISSUE TITLE
Shows "Playing now" when not playing

### ISSUE THREAD

**Issue by Wrascon** [JimmyAppelt/Snaz#164]
Before updating the application, I put it in OBS a long time ago. String with music played. It as well should not be shown on the screen when nothing plays. After updating, this inscription is always shown. I have "Ed Sheeran - 'Shape of You'" in the "Snaz / TextFiles / TrackInfo.txt" file and I did not listen to it. Especially since I do not have a file that I lost on my computer through VLC, In in output format is written only "'$ song`"

**Comment by JimmyAppelt** [comment]
Hi @Wrascon,

Indeed, I probably forgot to stop my own player, when closing Snaz and packaging the latest version. That why the 1.12.6.0 version probably is shipped with some song info text from myself.

**Comment by JimmyAppelt** [comment]
@Wrascon the file will clear when you played a song and stopped right ? Or when you choose the player "none" and then switched back to your actual player ?

**Comment by Wrascon** [comment]
Yes. I changed it yourself and they started working fine

**Comment by JimmyAppelt** [comment]
It's fixed for next update ... so it can't happen again.

**Comment by JimmyAppelt** [comment]
Will fix this for all text files soon ref #165
