### ISSUE TITLE
Missing Spotify Album Info

### ISSUE THREAD

**Issue by JustShogun** [JimmyAppelt/Snaz#166]
Hi, Sorry to report  I'm having an issue with Spotify album info after update 1.12.6.
Snaz isn't getting any album info, text or image from Spotify. Song & artist text are working. I've tried the usual restart/reinstall a couple times before coming here.
I read the thread for issue #159 which seemed the same but nobody mentioned the text and it was marked as closed so I though I should make a new report.
Thanks

**Comment by JimmyAppelt** [comment]
To get album and it's art it's required now to authenticate with Spotify. 1.12.6.0 will let you do that.

Documentation can be found here:
https://github.com/JimmyAppelt/Snaz/wiki/Spotify-API-credentials

I've added the doc link to the thread you mentioned, so it's clear.

**Comment by JustShogun** [comment]
cheers. I figured it was something on my end
