### ISSUE TITLE
Ability to use all UPPER CASE for song titles, etc.

### ISSUE THREAD

**Issue by broadcastguy** [JimmyAppelt/Snaz#167]
The plugin is awesome. I was just hoping you could add the ability to use UPPER CASE text to song title information. All of my lower thirds are upper case, so it looks a little out of place when song titles are the only thing that display uppper/lower.

Thank you!

**Comment by JimmyAppelt** [comment]
I'll implement it for 1.12.6.1

**Comment by JimmyAppelt** [comment]
You will be able to do this with the next parameters:

- $artist_upper
- $song_upper
- $album_upper
