### ISSUE TITLE
Countdown just not working?

### ISSUE THREAD

**Issue by Cloud557** [JimmyAppelt/Snaz#169]
So, I plan on doing a few streams sooner rather than later before the big release of Destiny 2, and I wanted to use Snaz to countdown during all of those streams until the release of Destiny 2.

I had used Snaz to countdown for another game once before and it worked fine then so I figured it would be fine this time, but when I loaded it up and set the countdown timer to the proper date and time and clicked "Start" it came back with this:

"Please pick a time that is later than the current time...

Start on application startup = False"

and when I change the start on application startup option in the settings, the only thing that changes is the "Start on application startup = False" turns to "Start on application startup = True"

I honestly have no idea what is going on, but it seems to me like this is a bug... Or I'm just really stupid, probably the latter...

**Comment by JimmyAppelt** [comment]
"Please pick a time that is later than the current time..."  ... I think you already noticed it (because you closed this) ... this means the countdown is set to a time that already has passed ... a countdown needs to have a time to countdown **to**.
