### ISSUE TITLE
Songtext gets blurry when OBS scene changed

### ISSUE THREAD

**Issue by CHEF-KOCH** [JimmyAppelt/Snaz#171]
OBS: 19.0.3 (it's anyway with every OBS version) it's running as Admin
Windows: 10 x64
Snaz: 1.12.6.0 (running without Admin privileges) 

1) Make a songtext via Browser source in OBS (e.g. for Spotify)
2) Add the songtext source to OBS.
3) Minimize Snaz to the tray. 
4) Do your stream/recording. Start/stop Spotify. Switch the OBS scenes. 
5) See blurry text. 

![animation1](https://user-images.githubusercontent.com/727123/27811190-dab14fb8-6063-11e7-9966-fae8c484bab1.gif)

It normally works well but something is broken if Spotify is stopped/started or Snaz is in system tray waiting.

**Comment by JimmyAppelt** [comment]
The rendering of the text is only related to the stream software. Snaz only writes the text to a file so the stream software can read it.
