### ISSUE TITLE
(Request) Allow a 'Minimize to Tray' Function

### ISSUE THREAD

**Issue by TechPhil** [JimmyAppelt/Snaz#173]
During Streaming, I often have a very busy taskbar, so being able to minimise apps to the system tray would be great, especially ones like Snaz which run peacefully in the background.

**Comment by JimmyAppelt** [comment]
That should already be the case when this setting is disabled

![task](https://user-images.githubusercontent.com/5420393/27987009-8be814b4-6407-11e7-861b-60e616d12018.png)
