### ISSUE TITLE
Timer jumping.

### ISSUE THREAD

**Issue by Az0na** [JimmyAppelt/Snaz#175]
I got tiny little issue no idea if its fixable or change it.

pictures says more then 10000 words so I made to screens.

can see example 1 fills lot less space then example 2, only happens when number 1 is used.

Tried aline text from right to left but still keep doing like example 1.

anyway fix this? text keeps aline from right? tried settings in obs but that doenst do anything
![example1](https://user-images.githubusercontent.com/30128793/28138656-dc9b52d4-6751-11e7-9163-33a11ae6e9b0.png)
![example2](https://user-images.githubusercontent.com/30128793/28138660-de59b890-6751-11e7-84d0-0065b39c49f6.png)

**Comment by JimmyAppelt** [comment]
Hi @Az0na 

That's related to the font you are using. Since n. 1 is less in width the n. 2 in that font. There is nothing I can do about that 😄
