### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by Drlanderf** [JimmyAppelt/Snaz#176]
Avec la dernière mise à jour de snaz j'ai de gros soucis avec le logiciel , en effet il fait ramer tout windows alors qu'il ne le fessait pas avant et il ne fonctionne plus trop bien , comment résoudre ce problème ?

**Comment by Drlanderf** [comment]
(le boutons fonctionnes 2 ans après le clic,... le logiciel ram trop et fait ramer (ps j'ai 16go de ram un i7 5820k et une geforce gtx 1070+SSD) mauvaise optimisation du programme

**Comment by JimmyAppelt** [comment]
Kindly use English

**Comment by Drlanderf** [comment]
So ok, after the last update i have some problems with snaz , freeze , "ram" and other.. i don't know how to resolve this , so i unstall , i clean up my pc don't work, it's a compatibility problem with last windows 10 ? (last update) ?

**Comment by Drlanderf** [comment]
and sorry for my bad english ^^'

**Comment by JimmyAppelt** [comment]
Try going into File > Settings > System Info and disable network meter. Should work fine for Windows 10 since I use the same setup :)
