### ISSUE TITLE
Temperature and Humidity

### ISSUE THREAD

**Issue by joseavarela** [JimmyAppelt/Snaz#180]
Please add a txt frome weather or other webpage to broadcast!!!

**Comment by joseavarela** [comment]
Spanish: Hola por favor si pueden agregar la opcion de generar un archivo txt de Temperatura y humedad desde las paginas que existen. gracias

**Comment by JimmyAppelt** [comment]
Hi, I'm sorry requests are closed currently closed.

Regards
