### ISSUE TITLE
Not sure if the right place to post, but can someone help?

### ISSUE THREAD

**Issue by jehovanova** [JimmyAppelt/Snaz#181]
I don't really know how to use dynamic files (I read the wiki but am still having problems). I just want to create a dynamic text file that pulls my total follower count from Twitch. Can someone help me with this?

**Comment by JimmyAppelt** [comment]
Hi @jehovanova,

I'm sorry but Git is not a help forum of any kind.

The wiki shows you a small [example](https://github.com/JimmyAppelt/Snaz/wiki/Dynamic-Files) of how to approach the dynamic file, however coding such file is up to the user.

Regards
