### ISSUE TITLE
[Request] Multiple time zones in the "Time" section

### ISSUE THREAD

**Issue by TWCSteven** [JimmyAppelt/Snaz#182]
Hello! I stream weather coverage on my YouTube channel and I use Snaz to display the current time, in eastern time. I'd be most interested if you added multiple time zones support. For example, I'd like to have ET, CT, MT, and PT.

I'll be very thankful if you added this feature! Thanks and have an amazing day.

**Comment by JimmyAppelt** [comment]
Hi, I'm sorry requests are closed currently closed.

Regards
