### ISSUE TITLE
Displaying album art from VLC media player

### ISSUE THREAD

**Issue by MartinBarker** [JimmyAppelt/Snaz#188]
Hi Jimmy,

I'm fairly new to Snaz, but so far I've gotten it to correctly display the song name and artist in OBS for music that I am playing in VLC media player. But I am running into an issue getting the album artwork to display.

Under the 'track info' text in the 'playing now' tab of Snaz, it does not show the artwork for the song currently playing my only instance of VLC running, even when that audio file definitely has album art which is shown in VLC.

The album art path is set to ' D:\Software\Snaz\Images\AlbumImage.png ' , and when I view this folder, the 'AlbumImage.png ' file is just a single pixel file. Any help would be appreciated! 

Thanks, Martin

**Comment by MartinBarker** [comment]
I see the 'album and it's art requires authentication now' statment at the top of snaz, does this mean it is impossible to get the current album art from vlc?

**Comment by JimmyAppelt** [comment]
This page contains all information you ask 👍  
https://github.com/JimmyAppelt/Snaz/wiki/Playing-Now
