### ISSUE TITLE
Mouse traveled distance in km

### ISSUE THREAD

**Issue by Lucas83** [JimmyAppelt/Snaz#19]
I remember, long time ago I had an app that was counting distance I moved by my mouse (I think it was configurable from size of screen, but it's not very important). It could be interesting function if program could count mouse traveled distance from start of a stream or since program starts.

**Comment by JimmyAppelt** [comment]
Hi @Lucas83,

This would be something for a separate program

Example: http://www.tucows.com/preview/279014/Mouse-Distance-Measurer

I would have no real clue why people would like to stream the distance that there mouse has traveled. I do understand that you would like to do it :smile:, but most people wont. I cant implement features that only concern one user.
