### ISSUE TITLE
iTunes doesn't work with it.

### ISSUE THREAD

**Issue by SpillProff** [JimmyAppelt/Snaz#191]
I wanted to use Spotify but my mp3's wouldn't work so I tried to use iTunes but then it thinks iTunes isn't open or it doesn't know iTunes is playing. About to stream later.

**Comment by rob2ee** [comment]
I opened a ticket for this 7 days ago.  No answer?

**Comment by JimmyAppelt** [comment]
@rob2ee  I know 

Patience dear .. I still did not found the time to look at it.

This issue is also a duplicate of #190

**Comment by rob2ee** [comment]
This is REALLY frustrating for me.  I really love SNAZ.  Is there an alternative app that works with iTunes that I can use until this is fixed?

**Comment by JimmyAppelt** [comment]
All programs using the same com component, which communicates with iTunes have the same error. So It's highly likely the new iTunes itself that invokes it.

**Comment by rob2ee** [comment]
Crap, is there a way to get iTunes to fix that?
