### ISSUE TITLE
Request - Adding a Change Title and Game option inside Twitch Viewers

### ISSUE THREAD

**Issue by sendblink23** [JimmyAppelt/Snaz#20]
Not sure if you want to implement this but can there be a possibility for you to add a Change Title and Game option inside Twitch Viewers... as in to us manually change the stream title(status) and game on the fly with your software?

Maybe make the Game/Status text box area editable with an update button under the Status word

**Comment by JimmyAppelt** [comment]
I would love to implement this. But i gonna have to think a bit on how i would best approach this.

The game/status update will require the user (like you) to authenticate snaz with twitch. Currently the twitch viewers tab can be used without authorize anything.

* So i ether have to authorize everything on that tab (meaning you can't put in another channel name then your own)
* I have to make a authentication button for only the game.status feature
* I have to make a new tab (something like "Twitch Dash") with features that you are able to use authenticated: update game/status, running ads etc.

Let me know what you would find best as user :+1:

**Comment by iamvroom** [comment]
I'd go with the same tab that there is now, just when the user has not authorized snaz to access the twitch account (i.e. like it is now) the text fields are grayed out. and hovering over the update field button would tell you to authorize (or even clicking would redirect you to tha auth site).

When it is authorized the text fields become editable.

**Comment by sendblink23** [comment]
If the suggestion by ^ iamvroom can be possible then go with that approach, if not then do the new tab "Twitch wte..."  :P  

Just keep it simple, If it can be done in the same tab of Twitch Viewers, then myself I would Eliminate the big Picture on the left side, then use that area to do the authorize and editable Game/Status. Then the right side simply is to show the updated change is working(as in to prove its 'live' the change).

A random Example:
![snazzy-edit](https://cloud.githubusercontent.com/assets/15650308/11455360/d4a946dc-9631-11e5-9023-cf6f978148dc.png)

**Comment by JimmyAppelt** [comment]
@sendblink23 @iamvroom thank you for the great insight

**Comment by iamvroom** [comment]
@JimmyAppelt np, trying to contribute to a really good useful piece of software :)

**Comment by JimmyAppelt** [comment]
Expect it in the next release :rocket:
