### ISSUE TITLE
Make tab "Twitch Viewers" be more useful

### ISSUE THREAD

**Issue by Lucas83** [JimmyAppelt/Snaz#22]
It could be great to make tab "Twitch Viewers" be more useful. For now it's possible to get only current viewers count into TwitchViewerCount.txt, but this tab also monitoring Game, Status, Followers, Views and so on. So maybe it could be an option to save these information to other txt files?

**Comment by JimmyAppelt** [comment]
Hi @Lucas83,

I could implement this indeed, the dynamic files feature is actually a solution to request 
anything you like from any server. (But you probably have seen they are 404'ing right now. (they caused a to big server load and now my website is suspended ... for that).

I'm digging in all sorts of solution and will see what fits best.

I will mark this as enhancement (i will see what the best option is to make this work)

**Comment by JimmyAppelt** [comment]
In case you don't have a server for your own to host php files then:

The easiest option, is to run `XAMPP` (or something simmiliar) on your machine and host the `.php` file(s) for yourself locally.

> If you need the .php files, then come and join on discord (me or a fellow chatter will give you a pack trough there)

**Comment by iamvroom** [comment]
Wouldn't it be possible for dynamic files to be hosted off of the regular file structure?

**Comment by JimmyAppelt** [comment]
> Wouldn't it be possible for dynamic files to be hosted off of the regular file structure?

Please elaborate ?

**Comment by iamvroom** [comment]
instead of having to grab them off of the http:// maybe make it possible to read files off of the hdd as well e.g. C:\test.txt

**Comment by JimmyAppelt** [comment]
Why would you have the need to get a local file with dynamic files ?

A local file is static, not dynamic :star: 
(And if the static file changes your stream software will pick it up and redraw it)

You could place a local file directly in your stream software ...

> The purpose of Dynamic Files is to get *online* content and make it "local" static, so a stream software can read it.

> This is also barley on topic `Make tab "Twitch Viewers" be more useful`

**Comment by iamvroom** [comment]
ya, true

**Comment by Lucas83** [comment]
Thanks for answer @JimmyAppelt - I realized that and I run such checking from my localhost using wampserver.
