### ISSUE TITLE
Option to disable Current PC time / date saving to file at start

### ISSUE THREAD

**Issue by Lucas83** [JimmyAppelt/Snaz#25]
After I start Snaz then it starts working on files, for example - saving every second current PC time in txt, even if I don't use it. Since it's possible to disable Chronoup and other functions at start, so maybe it could be nice option to disable this as well?

I'm asking about that, because constant save to disk isn't very healthy for his long life (at least I heard ;) )

Or - if I use to show time in hours and minutes (without seconds) then it's no needed to save to file every second :)

**Comment by JimmyAppelt** [comment]
Hi @Lucas83 

If you empty the format box of the specific feature it will be disabled and will not write any files to the disk.

**Comment by JimmyAppelt** [comment]
Dynamic files will only write when new content is detected in the next release 1.12.1.0 :star:

**Comment by JimmyAppelt** [comment]
I will take that this resolves your issue/request.

If it is not, please feel free to open a new ticket :+1:
