### ISSUE TITLE
CPU Temperature

### ISSUE THREAD

**Issue by Lucas83** [JimmyAppelt/Snaz#28]
Since such great idea like CPU usage exist, then maybe it could be also interesting to add CPU temperature as well to System Info tab? Unless it's difficult to implement.

**Comment by JimmyAppelt** [comment]
There is no generic way to do that - it depends on the motherboard manufacturer.

**Comment by Lucas83** [comment]
I heard it's possible by WMI (Windows Management Instrumentation).

https://msdn.microsoft.com/en-us/library/aa389273(v=VS.85).aspx

**Comment by JimmyAppelt** [comment]
That would be a a way to get the data indeed, but its not supported for all motherboards.
