### ISSUE TITLE
Text line updates missed by OBS

### ISSUE THREAD

**Issue by paulheu** [JimmyAppelt/Snaz#29]
Not sure if it's a bug or even an issue with Snaz, but it seems that OBS keeps missing text line changer changes somehow.. Sometimes need to start stop several times to get it to update or even disable en re-enable lines

**Comment by JimmyAppelt** [comment]
Hi @paulheu,

A few things i would like to know, before trying and replicate the problem.
* Is there anything special to notice on what your content is of those text lines ?
* What version of OBS are you using/testing and what is the interval of the text line changer ?

**Comment by paulheu** [comment]
It's short text with small changes (a few characters). The OBS version I use is 0.657b

The issue is not consistent although it is frequently happening and may take several attempts to resolve when it does

**Comment by paulheu** [comment]
Did a late stream today and actually had to quit Snaz to update the text.

The text lines read the number of times I cash or bust in the game the line represents (playing poker) and the amount I'm up or down for that game. So changes are a few characters per line.

Changing the cycle time did not make a difference, generally if I disable one line, start the cycle, stop it and re-activate the line itwill update next time I hit start, but not always.

**Comment by JimmyAppelt** [comment]
hey @paulheu 

There must be something i'm missing here as i'm unable to replicate this kind of behavior.

Could you maybe share a screenshot of how snaz looks like so i have a better understanding ? And do you add lines at runtime ?

**Comment by paulheu** [comment]
Here's the XML for the lines I use. I do change the amounts and the 0c/0b (number of cashes and busts) while streaming and the rotation is running yes.

<?xml version="1.0" encoding="utf-8"?>

<TextLines>
  <Line Active="True" Random="True" String="Results For Day 19" />
  <Line Active="True" Random="True" String="Tournaments 0c/0b $0" />
  <Line Active="True" Random="True" String="Spin&amp;Go 0c/0b $0" />
  <Line Active="True" Random="True" String="SnG 45p Turbo 0c/0b $0" />
  <Line Active="True" Random="True" String="Bankroll change $0" />
</TextLines>

**Comment by paulheu** [comment]
Having same issue again right now, would not update until I saved the XML and reloaded it

**Comment by paulheu** [comment]
As discussed I tried using the OK button instead of hitting return and that works fine as far as I can see. So the issue is with hitting return. I'd prefer to keep the return option, but if it's easier to disable that and force clicking OK that would work (for me) for now too..

**Comment by JimmyAppelt** [comment]
> OP has a 1.12.1.1 client to test

**Comment by paulheu** [comment]
It looks to be working fine now.. tx for the quick fix..

**Comment by JimmyAppelt** [comment]
@paulheu 

Great thing :+1: 

If you experience it again, don't hesitate to open a new ticket :smile:
