### ISSUE TITLE
Text timer - unlock 1000 limit please.

### ISSUE THREAD

**Issue by mannymation** [JimmyAppelt/Snaz#3]
Hey man, im actually capturing the animated bar for the text timer as well. And I am using it to show when i switch between projects every hour or two.
The problem atm, is that its limited at 1000 seconds by code, and id like to be able to put in 3600 for the hour and 7200 for the 2 hour switch.

Any chance you can unlock the 1000 restraint ?

Much thanks, love the app!

**Comment by JimmyAppelt** [comment]
Hey Manny,

I will unlock this in the next release for you :+1:

**Comment by JimmyAppelt** [comment]
Snaz window will startup on the same location as where you closed it also in the next release. It will be easier when you would like to capture the bar or something else with window capturing :star2:

**Comment by mannymation** [comment]
Sweet! When r u pushing this out friend?



On Monday, October 5, 2015, Jimmy <notifications@github.com> wrote:

> Snaz window will startup on the same location as where you closed it also
> in the next release. It will be easier when you would like to capture the
> bar or something else with window capturing [image: :star2:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JimmyAppelt/Snaz/issues/3#issuecomment-145495449>.
>


-- 
            _______

          *Manny Llamas*
        www.artbymanny.com

**Comment by JimmyAppelt** [comment]
@mannymation somewhere between end of the week beginning next week. Need to a tiny bit of work on the new spotify feature and testing before deploying.

**Comment by JimmyAppelt** [comment]
Unlocked in 1.10.0.0
