### ISSUE TITLE
No source available.

### ISSUE THREAD

**Issue by cotti** [JimmyAppelt/Snaz#30]
Hello.

The project website states that Snaz is "Free Software", which made me really happy since it works really well. But I came here and Github is being used solely as a Issue/Suggestion tracker.

Any plans on making it actual Free Software, offering the source code for people who can get the binary release?

**Comment by JimmyAppelt** [comment]
hi @cotti 

Snaz is currently free to use, that is correct.

> making it actual Free Software, offering the source code

Free software is not the same as open source software :wink: 
Will i release it ever opensource ? Maybe... but this was never the intention.

**Comment by JimmyAppelt** [comment]
Changed to "Freeware", will also be updated in client next update.

Thanks
