### ISSUE TITLE
Allow Keyboard Hooks shortcuts to be re-assigned

### ISSUE THREAD

**Issue by Slegnor** [JimmyAppelt/Snaz#31]
The change for Keyboard Hooks to CTRL+F9 to CTRL-F12 etc does limit conflict with other programs but I would be better if they could be remapped to keys of the user's choosing.

**Comment by JimmyAppelt** [comment]
Making by user choice hooked shortcuts, is a pretty big job (these are not normal keyboard shortcuts for a program).

The mapped once CTRL+F9 and etc. came best out when the BETA was on.

> conflict with other programs 

What kind of programs ?

**Comment by Slegnor** [comment]
Mostly with games, DayZ, ARMAIII, MMOs, especially have a lot of key binds available and CTRL+FKeys are used in a lot of them

**Comment by JimmyAppelt** [comment]
We believe that Ctrl+F9 ... etc.. are one of the less used shortcuts out there. Of coarse some game can have one or some of these defaulted.

Don't think there is a better (pretty simple combination) out there.

The only way to dis-encounter this is making the key binds by user choice.

**Comment by Slegnor** [comment]
"The only way to dis-encounter this is making the key binds by user choice"

That's what I was trying to suggest, maybe it didn't come out right in the original post.

CTRL-F9 etc as default, but the ability for the user the redefine them

**Comment by JimmyAppelt** [comment]
Will be available from 1.12.5.0 or above.
