### ISSUE TITLE
Request - Manual counter with global hotkey (e.g. death counter)

### ISSUE THREAD

**Issue by roncli** [JimmyAppelt/Snaz#32]
I'd love a feature where I can hit a hotkey and have a simple counter get incremented.  Great for tracking things like deaths, how many times you've done something, or anything arbitrarily fun.

**Comment by Lucas83** [comment]
Yes, it's good idea. I would like to add a short sound played after you pressed such button, to make sure you didn't press too many times (and it's hard to find out while you're in the game and you don't see stream window).

**Comment by Montclair** [comment]
You can do this easily with Autohotkey. Bind a key to increment a variable and write it to a file and optionally play a sound. Tie an OBS text box to the file and you're done. Google Autohotkey for more info.

**Comment by joXnka** [comment]
+ +one for this please :+1:

**Comment by JimmyAppelt** [comment]
@joXnka the idea is to up vote whit a thumbs up on the first post.
