### ISSUE TITLE
Ram usage without decimal values

### ISSUE THREAD

**Issue by Lucas83** [JimmyAppelt/Snaz#33]
In System Info tab Snaz is monitoring CPU usage without decimal values, and it's simple, explicit value. So maybe percentage in ram usage could be as well without decimal values, in the same way as CPU usage is presented? Also this might apply to Ram Available in MB, maybe it should be converted to GB value, since it could be easier to read (for example instead of 4441 MB could be 4,3 GB).

**Comment by JimmyAppelt** [comment]
Will be settings available for this in next release :+1:
