### ISSUE TITLE
have $followers as tag in "Twitch viewers" tab 

### ISSUE THREAD

**Issue by rob-w** [JimmyAppelt/Snaz#34]
as the title says .. would love to have $followers as current foillowers in "Twitch Viewers" tab .. thx

**Comment by JimmyAppelt** [comment]
@rob-w 

You do know that you can get this information with dynamic files already, yes ?

**Comment by JimmyAppelt** [comment]
@rob-w if you still have a question about this, feel free to reopen it

Closed: No interaction
