### ISSUE TITLE
Playing Now support for RadioDJ

### ISSUE THREAD

**Issue by paulheu** [JimmyAppelt/Snaz#40]
RadioDJ (http://www.radiodj.ro/) is a rather nice automated radio application which has excellent random playback. WIth Spotify not capable of handling my local music library (it seems as it keeps crashing) I am looking to use this as the random playback is much abtter than Foobar and it has neat features such as not playing the a track from the same artist within x amounts of minutes.

It has the ability to output the current track title to a textfile but no album art..

Would it be possible to add support in Snaz to read the current track from a textfile in a format like $artist~$song~$album and grab the album art from that? While RadioDJ has a way to do this it's rather cumbersome..

**Comment by paulheu** [comment]
Actually.. never mind.. ;)

**Comment by JimmyAppelt** [comment]
I actually just installed everything to see that `playing now` is already in there :)

**Comment by paulheu** [comment]
lol .. ok.. switched to foobar as I need to do some more setup..;)
Will have a look at it later though as RadioDJ is an interesting program to use..
-Paul


Date: Sun, 27 Dec 2015 05:14:13 -0800
