### ISSUE TITLE
Ticker tab

### ISSUE THREAD

**Issue by paulheu** [JimmyAppelt/Snaz#42]
Similar to Text line changer, but instead of showing lines separately, join all lines into one single line of text with an optional separator (like "    ....    ")between them so you can show them in a scrolling ticker

**Comment by Montclair** [comment]
Couldn't you just do this with OBS itself? This rather defeats the purpose of the line changer, no? I mean, put all the text you want into a single text box and scroll it in OBS. Done.

**Comment by paulheu** [comment]
creating a scrolling ticker becomes easier if you can enter separate lines which are then joined into one in the file which is then used in OBS

**Comment by Montclair** [comment]
I still don't understand this request. Use notepad and enter all the lines you want. Point obs to the file. Done.

**Comment by paulheu** [comment]
Sure it can be done manually, If I use a tool which does  number of text things for me though, it would be a nice function to have for my purpose. That you do not need this, or think you do not need it is obviously fine. I think that it would be handy to have an option to set up segments of a ticker on separate lines and then have it output to a single line text file with separators. Makes editing the bit in the middle a lot easier.

**Comment by Montclair** [comment]
I wasn't trying to be combative. My appologies. I eas just trying to help you as the tool you need already exists. Notepad will do exactly what you want. Separate each line with a carriage return and you'll easily be able to access any of them. OBS will discard the carriage returns and you'll have what you want.

Does this...
Make it easier...
To see...
My suggestion...

Output: Does this...Make it easier...To see...My suggesstion...Does this...Make it easier... (etc)

**Comment by paulheu** [comment]
I get your suggestion, have a macro in Notepad++ doing it now. Would just be nice to have all my text stuff in one tool is all.
