### ISSUE TITLE
YouTube / Hitbox Viewers

### ISSUE THREAD

**Issue by Montclair** [JimmyAppelt/Snaz#43]
Would love to have an option to combine YouTube, Twitch, and possibly Hitbox viewers into one, or at least, have the option for the others available as separate tabs.

**Comment by JimmyAppelt** [comment]
Hi @Montclair,

I'm not sure if i would add add these in the UI immediately, however ...

This is one that would be a perfect job for the `Dynamic Files` feature. I already have the files ready to use with `Dynamic Files` for Hitbox and Twitch. This file pack is available for download in the discord chat.

As for youtube i have to write a file for that, but that should be any problem to do.

With `DF` its easy possible to get these values separate and/or combine theme as one. 

*(You could see `Dynamic Files` as a sort of a plugin manager, where external files will do the specific task and snaz handles the result)* 

Always happy to answer any questions regarding `DF` in our chatroom

**Comment by Montclair** [comment]
If you have the time and could write a file to combine YouTube and Twitch, that would be awesome!

**Comment by Montclair** [comment]
Any chance of providing this soon?

**Comment by JimmyAppelt** [comment]
@Montclair it's not a priority at this time i'm afraid. I have to dive in the latest YouTube API for that (v3) since you specify YouTube.

**Comment by MakerTim** [comment]
Hitbox api is way to dynamic to use; its updating every day... no back compatibility most of the time...

**Comment by majorasic** [comment]
So there is no chance to get a Hitbox and Twitch viewers ?

**Comment by JimmyAppelt** [comment]
@majorasic if you write a .php file for it ... then you can get it with dynamic files.

**Comment by JimmyAppelt** [comment]
Due to having time constraints and nothing really software hardcode related, i will close this issue.

Will leave the `.php` file coding for the great geeks out here :)

If someone is nice enough to share such `.php` file, feel free to re-open this ticket.
