### ISSUE TITLE
Music Player

### ISSUE THREAD

**Issue by xDxK** [JimmyAppelt/Snaz#44]
Add the following Radios with .txt for OBS :)
TuneIn.com
energy.de
housetime.fm
technobase.fm
hardbase.fm

Thanks :)

**Comment by JimmyAppelt** [comment]
hey @xDxK 

* housetime.fm
* technobase.fm
* hardbase.fm

These are all streaming services.

* energy.de

I'm unable to access there website on the moment of writing (if this is a one language player only - i will not integrate it)

* TuneIn.com

Is currently not available for windows (as far as i can see)
