### ISSUE TITLE
Exclude certain patterns before doing a album image query job

### ISSUE THREAD

**Issue by paulheu** [JimmyAppelt/Snaz#45]
Album art is not showing for extended file names. generally tags for title will have things like (album version), [12inch version] or (thisguy's mix). This will not find album art unless the title is exactly as the database says. Removing the added text from the title would show the album art shortly after

A fix would be to offer the option to add the option to ignore such extensions, maybe with the ability to add your own (in settings)

**Comment by JimmyAppelt** [comment]
hi @paulheu 

The album art is fetched base on the artist name and the song title indeed. If one of these two are incorrect, then no result will be found in the database.

That means essentially that ` [12inch version]` or `(thisguy's mix)` does not truly belong to one of these parameters.

After a small chat ... it became more clear about the request. 

> Having an list option, to exclude certain patterns before doing a query job to the server
