### ISSUE TITLE
1.12.2.0 wont launch properly

### ISSUE THREAD

**Issue by heater07** [JimmyAppelt/Snaz#46]
So I used 1.12.2.0 for a few days, rebooted and then when I launch Snaz, the window is in lower left part of screen. Only thing I could do is maximize it, but the window is locked and I get error tone every time I try to click in the application.

So I uninstalled, launched setup again, and the setup I have is version 1.12.1.2.  This installs fine, window comes up center screen and I can edit all tabs like normal, however, as soon as I updated back to 1.12.2.0, when app starts, its back to the state of being locked where I cant move window title, or click anything. No idea what caused this!

**Comment by heater07** [comment]
After further troubleshooting, I think this has to do with the "Start on application startup = True".
I get an error that says Please pick a time that is later then the current time..., however, before I wasnt actually seeing the error because I believe it was being started as minimized.

I was able to test this by swapping out user.config files from different versions, and when I used the older config I was able to launch 1.12.2.0 without getting any errors.

**Comment by JimmyAppelt** [comment]
hi @heater07 

`Please pick a time that is later then the current time` is not an error is a information box, which means that the time chosen in the countdown already passed the current real time. 
`Start on application startup = True` is because in the countdown settings `Start on application startup` is checked.

To reset the whole `user.config` you can delete the `C:\Users\YOUR_USERNAME\AppData\Local\JimsApps` folder after you have closed Snaz first, and then restart snaz.

A default configuration file will be made and should work properly.

**Comment by heater07** [comment]
@JimmyAppelt 

Im not so much concerned with the exact error, but why after a reboot, the app was at the lower left of my screen, unable to even see the error, move the app, etc.  I heard the error tones, just couldnt see any errors to acknowledge.

**Comment by JimmyAppelt** [comment]
@heater07 my suspect is that the configuration file was corrupted somehow. The way it went corrupted  is obviously a big guess.

The configuration file contains settings that remembers the location of Snaz's window position etc. , if it gets corrupted somehow ... then its possible that the window will not appear.

**Comment by heater07** [comment]
Ok thanks for the response, figured I would let the dev know as I thought it was kinda odd.  It was odd that even when I was able to maximize it, I couldnt find the popup box that was generated, it was like hidden.  If this happens again I will just delete the config file.

**Comment by JimmyAppelt** [comment]
Yeah, if the box is Snaz generated it will pop up in the middle of the Snaz window.

Appreciate any reports sir, thank you.

If you have any other issues in the future feel free to make a new post.

**Comment by JimmyAppelt** [comment]
> When this happens Snaz will prompt you to ask if you want to fix this automatically from 1.12.4.3
