### ISSUE TITLE
Countdown "presets"

### ISSUE THREAD

**Issue by c0dycode** [JimmyAppelt/Snaz#47]
First of all, great app you made there :) I really like it so far.

For the request,

I'm not sure if this has been requested before, or maybe I'm missing it, but my idea would be to either add a button for like increasing the countdown by +5 with a simple "+5" Button. Or maybe add it to the options so people can choose their own time for the preset button.

Or add a button to switch between the current countdown-layout and something like this:

![Example Layout](http://i.imgur.com/3k3lefu.png)

:)

**Comment by JimmyAppelt** [comment]
hi @c0dycode 

Thank for making you're request, although i'm unsure what you are trying to ask ?

As you refer ... i suspect the feature you are talking about is the `Countdown to specific time`

You can already increase every value separate ... if you select minutes for e.g. and press the up button it will change live (by 1 value at a time)

If i do understand your request wrong please elaborate some more (forgive me if i do :smile: )

**Comment by c0dycode** [comment]
Hey @JimmyAppelt 

oooookay. So after trying to explain it as easy as possible I just saw that the "Chrono Down" basically does the same thing that I wanted to suggest.

Sorry 'bout that :P 

And as I've discovered this now, is it planned to be able to start the Chrono Down on startup? If so, consider this "request" fulfilled :+1:

**Comment by JimmyAppelt** [comment]
> Sorry 'bout that :P

No worries :smile: 

For the `Start Chrono Down on startup` is not planned at this time but can surly be implemented.

I've just added it to the todo list #48 - so its planned now :smiley:
