### ISSUE TITLE
Suggestion: Add option to ceil / round up counters

### ISSUE THREAD

**Issue by Nixxen** [JimmyAppelt/Snaz#5]
Not sure how to form a suggestion here, so I'll drop it here in hopes that you'll see it.
In countdown or Chronos, having the option to ceil or round up a value would be great.

In Chrono's Down for instance "Stream starts in: $m min":
Start timer at 15min.
Currently it will count 14, then 13 and so on until it reaches 0m despite there being seconds left on the clock.
When ceiled it would read 15 (while the actual value could be 14m30 sec), and continue 1 minute "above" the actual time value until the final "Msg when done" string is shown - Most importantly "Stream starts in: 0 min" will never happen.

**Comment by JimmyAppelt** [comment]
For chrono down in 1.12.1.0 release this will go automatically.

If the format box doesn't contains `$s` (seconds mark) it will be done at `0 minutes`.

> Just bare in mind that if you would like to do a 15 minute countdown you start the chrono down at 16 minutes (Because we will not count the seconds to zero anymore).
