### ISSUE TITLE
Add iTunes to Playing Now

### ISSUE THREAD

**Issue by rymonds** [JimmyAppelt/Snaz#50]
can you sync iTunes to snaz?
i would be happy if that could be done.

**Comment by JimmyAppelt** [comment]
I will add iTunes in the future, depending on support from snaz users.

**Comment by rymonds** [comment]
so happy!! I'm looking forward to that day.

**Comment by JimmyAppelt** [comment]
Will be available in 1.2.3.0 release, once it is out of beta.

![1969f3d399c139214343630bdf135cde](https://cloud.githubusercontent.com/assets/5420393/18024683/a27fc608-6c10-11e6-86c4-d8348fc19c47.png)

**Comment by JimmyAppelt** [comment]
Docs: [https://github.com/JimmyAppelt/Snaz/wiki/iTunes](https://github.com/JimmyAppelt/Snaz/wiki/iTunes)

**Comment by JimmyAppelt** [comment]
Hi @rymonds 

Would you be willing to beta test iTunes Sir ?

**Comment by rymonds** [comment]
wow!! sooo thank you for good work!!
>
>you totally rock
>
>
>i had been longing for your message XD
>i try it immediaterly!!
>May you have many more successful  to come...
>
>
>

**Comment by JimmyAppelt** [comment]
@rymonds 

The beta's are downloadable trough our discord server. I will need you're login name to (since only beta testers get access)

You can login into the discord trough the Help > Chat (Discord) menu

**Comment by rymonds** [comment]
all right thx!
i try it
