### ISSUE TITLE
Add twitch chat to stream

### ISSUE THREAD

**Issue by Elfranko** [JimmyAppelt/Snaz#51]
Would it be possible to make Snaz display twitch chat on stream?
This would make Snaz perfect. With the features already in Snaz, there would not be a need for other apps in combination with Snaz.

Keep up the good work!
Regards,
Frank

**Comment by JimmyAppelt** [comment]
hi @Elfranko 

There are a lot of things that i could add ... that other apps do. The main thing is that a feature like this is/was not really intended to put in. As Snaz was originally a text file writer.

Now yes, it has grown out a little bit, here and there.

I was thinking of re-writing/re-designing Snaz (with a whole lot more of features) but this is a pretty big job of coarse. As till today Snaz is lacking donation support to create the time and make this reality. 
Would love to create all this stuff in one application ... but for now i have to put my time on jobs that pay the bills.

**Comment by iamvroom** [comment]
Twitchalerts etc. already display the chat - why make snaz cover the same ground 10 other applications already do?

**Comment by Elfranko** [comment]
Thank you for your answer @JimmyAppelt 
I will cross my fingers for Snaz to have this feature after an eventual rewrite;)
And of course this is only a request. In no way is this an expectation. I fully understand that you have to focus on the job that pays the bills.

@iamvroom 
Your point is moot. Why make a now playing feature, or a game/status updater in Snaz then, when there are applications like Snip, Teeboard etc. to do the same?
The point was to only have to use one application to do everything, instead of having 2, 3, 4 different apps to do different things. A feauture like this would only make Snaz better in my opinion.
I am sorry that my point was not clear enough in my first post.

Have a nice day guys:)

**Comment by iamvroom** [comment]
@Elfranko Every point is moot if it is against your own opinion XD

**Comment by JimmyAppelt** [comment]
@iamvroom please only comment with constructive and valuable feedback please, thank you :+1:

**Comment by JimmyAppelt** [comment]
After thinking about it for a while, i decided to not implement twitch chat. Snaz was never ment to do this and this feature would be overkill for a text file generator.

But then again, thank you for you're request
