### ISSUE TITLE
Bug in ID3 tag decoding

### ISSUE THREAD

**Issue by paulheu** [JimmyAppelt/Snaz#52]
Found a bug in the ID3 decoding. I see this on a lot of tracks. I have an archive set up as it seems I can't add the zip here. It's at:
http://1drv.ms/1ZzfYgs

Issue is that this track will show some additional info not in either the artist or title tag. When I remove the album tag it shows correctly. As a result of this bug the album art is not found unless you remove the album tag..

files;
mp3 file with tags showing the issue
snaz snapshot before the removal of the album tag and one after
foobar snapshot before and after

**Comment by JimmyAppelt** [comment]
@paulheu thanks for the detailed bug report (awesome) i'l check it out

**Comment by JimmyAppelt** [comment]
hey @paulheu 

Now i see what's happening :smile:. I actually made a solution to issue's like this.

First let me tell you why its behaving like that ...

*The window title original:*

![image](https://i.gyazo.com/5edb060ced07fc41955e44d604994f9d.png)

I have written an algorithm to extract all the information from this ... the character `]` appears more then once in this tittle. My algorithm cuts of the first `]` ... so here we receive `CD2 #06] Honey (So So Def Mix featuring Da Brat & JD)`

Now for issues like this in foobar2000 i implemented `Custom capture (Expert)`

Detailed information about this can be found on this page:https://github.com/JimmyAppelt/Snaz/wiki/Foobar2000

The Custom capture notation uses another algorithm. To make it work you have to change the window notation of foobar2000 in:

`%title% '♫' %artist% '♫' %track artist% '♫' %albumartist%`
