### ISSUE TITLE
'No Media Playing' text flickers

### ISSUE THREAD

**Issue by Slegnor** [JimmyAppelt/Snaz#55]
Bug with "Playing Now" tab - the "No Media Playing" optional text.

The displayed text flickers when displayed and occurs regardless of OBS being configured to have the text scrolling or static and it is unaffected by the font type or style effects applied to the font.

The "Live Output" text from "Now Playing" tab does not flicker.

![media](https://cloud.githubusercontent.com/assets/11891577/12467272/03f4ff70-bfd2-11e5-8e6c-d00be8a852eb.gif)

Using OBS x64 v0.657b

**Comment by JimmyAppelt** [comment]
hi @Slegnor 

Thank you for bringing this issue to my attention :+1: 

I pushed out 1.12.2.1 just now with a fix for this

**Comment by Slegnor** [comment]
Confirmed it is now fixed

**Comment by JimmyAppelt** [comment]
> Confirmed it is now fixed, nice work

Great ! Thanks again
