### ISSUE TITLE
Update Game/Status WITH Playing now

### ISSUE THREAD

**Issue by keawepoo** [JimmyAppelt/Snaz#58]
Is there a way we can have it so we can update Game/Status with whats Playing now + text + game from a text file just like how it is with the Playing Now??

Thank you.

**Comment by JimmyAppelt** [comment]
HI @keawepoo,

With the current version of Snaz, no. I'm afraid some feature like that is more for precise to the user. (Like you)
I have to focus on features and enhancements that is for better use for most people.

It is possible to code such thing of coarse ... but from my viewpoint right now, it will not be in Snaz.

I'm sure this is a strict answer to you're question, so i will close this issue (request).

In case you have more questions about this, feel free to re-open it.
