### ISSUE TITLE
Mac support

### ISSUE THREAD

**Issue by CliftonMarien** [JimmyAppelt/Snaz#62]
Please.  We really need Mac support.  I'm struggling to find an alternative.

**Comment by JimmyAppelt** [comment]
Hi @CliftonMarien 

Check out Wine https://www.winehq.org/

**Comment by CliftonMarien** [comment]
@JimmyAppelt I already have it installed.  The installer for Snaz crashes when I use it.  Do you have just an exe?

**Comment by JimmyAppelt** [comment]
Here is a zipped one ...
[Snaz.zip](https://github.com/JimmyAppelt/Snaz/files/143863/Snaz.zip)

**Comment by JimmyAppelt** [comment]
Closed due to non activity from OP
