### ISSUE TITLE
system failed to initialize

### ISSUE THREAD

**Issue by lordvapor87** [JimmyAppelt/Snaz#64]
having a critical error where on startup or shutdow of the program i hit a critical error that renders the program unusable it says system failed to initialize and then shuts down.

**Comment by JimmyAppelt** [comment]
Do you have a message box with a specific error ? Or did you meant `Configuration System Failed to Initialize` ?

If so, then:

- Delete the `JimsApps` folder in `C:\Users\YOUR_USERNAME\AppData\Local`
- Restart Snaz

**Comment by JimmyAppelt** [comment]
Ticket closed due no feeback
