### ISSUE TITLE
Write Spotify Now Playing as a JSON file

### ISSUE THREAD

**Issue by JohannJivaro** [JimmyAppelt/Snaz#65]
Great program!

Giving an option to write Now Playing to a JSON file would make it easier to customize the presentation of the music info and use in html overlays.

**Comment by JimmyAppelt** [comment]
Will be available in release 1.2.3.0

The file `track-info.json` will be available in the `Data` folder

![a479ad02a54ed93af66690e390085c03](https://cloud.githubusercontent.com/assets/5420393/17915896/92b1f6ec-69ae-11e6-8818-14078787e0b0.png)

![314b16f2df07e3ddfcbc6c6e2709479f](https://cloud.githubusercontent.com/assets/5420393/17915900/977efbfc-69ae-11e6-99d6-3db9091cbb8d.png)
