### ISSUE TITLE
Time Display: Hour format

### ISSUE THREAD

**Issue by Teh-Lord-Coley** [JimmyAppelt/Snaz#67]
I have noticed that the time display does not give you an option to remove the 0 (zero) from the front of a single digit hour. I really cannot stand the way that looks, no matter how I play with it's position on screen. It's very heckling. If it would not be too difficult, or too much of a burden, could you make it possible to format the hour without a zero in front? I would greatly appreciate this option. Thank you for your time and effort! ^_^

**Comment by JimmyAppelt** [comment]
hi @Teh-Lord-Coley ,

Will implement this in one the next updates for you

**Comment by Teh-Lord-Coley** [comment]
Amazing! Very appreciated~

**Comment by JimmyAppelt** [comment]
Available from 1.2.3.0
