### ISSUE TITLE
Snaz not starting properly

### ISSUE THREAD

**Issue by GERIskillzZz** [JimmyAppelt/Snaz#68]
Hey,
I just installed Snaz and when I try to start it, it takes almost 10 minutes. While this time, Snaz uses ~60% CPU. 
I'm using Windows 10, but I think that's not the problem, since when it started up after waiting this time, it works perfectly.
Maybe you could provide me with an older or outdated version, to see if this fixes the issue?

Greetings,
Max

**Comment by JimmyAppelt** [comment]
Hi @GERIskillzZz 

60% is out of bounds :), at this time there has no such issue reported before. I use win 10 myself and snaz is running nice and smooth on it. 

What features are enabled ? 

You can download older versions of Snaz here [https://github.com/JimmyAppelt/Snaz/releases](url)

**Comment by GERIskillzZz** [comment]
Thanks for the fast answer,
Yeah it's not 60% I misspelled. It's eating like 25%, but all in all my CPU-Usage is 60% then, I just looked at the wrong value in the Task Manager

I only use the Countdown in Snaz, so there is not much enabled.

I just installed the last 3 Versions, and everyone of them will not start up properly. I don't know how this is technically even possible o.O

Here's a screenshot of the newest Snaz Version after waiting for ~7 minutes: http://imgur.com/DC6VVFP

**Comment by JimmyAppelt** [comment]
If you are able to join the Discord server, then i can take a look on you're system with teamviewer if you like.

**Comment by GERIskillzZz** [comment]
@JimmyAppelt Yeah, that's a good idea. I will join it, when I get Snaz to start :D

**Comment by GERIskillzZz** [comment]
Okay, really weird. I've updated my Windows 10 yesterday to the newest Insider Preview, and now Snaz works perfectly... That's really strange... So my problem is solved now. 
Just for your interest: I now use Enterprise Build 14316..

**Comment by JimmyAppelt** [comment]
Are you sure its not just a system restart that did the trick ?

**Comment by GERIskillzZz** [comment]
No, I used Snaz for some days now, and this issue was there since the beginning. I don't really now it got fixed, but it works now.. Or maybe the installing of an older version, and then updating it fixed it. I don't really know.

**Comment by JimmyAppelt** [comment]
Well, glad its fixed and working for you :+1: 

Regards
