### ISSUE TITLE
Proposal: French Translation

### ISSUE THREAD

**Issue by mrmazure** [JimmyAppelt/Snaz#69]
Hello Jimmy,
I like your program, I use it daily. But I am sometimes disappointed, is it not able in French (just for export to date for exemple). I'd like to help to translate the app in French. This proposal does interest you? In what form can I send you a translation?

**Comment by JimmyAppelt** [comment]
Hi @mrmazure 

Thanks for you're support. But i will not make any translation available for snaz in the future.
