### ISSUE TITLE
Can't connect to Spotify 

### ISSUE THREAD

**Issue by hellnano** [JimmyAppelt/Snaz#7]
Snaz can't connecto to Spotify giving constants dialog of retry.
http://prntscr.com/8rto53

Giving this .NET error (v4.6)
----------------------------------------------------------------------------
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at Snaz.MainForm.a(TrackTimeChangeEventArgs A_0)
   at SpotifyAPI.Local.SpotifyLocalAPI.<ElapsedTick>d__34.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c__DisplayClass2.<ThrowAsync>b__3(Object state)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
Snaz
    Assembly Version: 1.10.0.3
    Win32 Version: 1.10.0.3
    CodeBase: file:///C:/JimsApps/Snaz/Snaz.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
SpotifyAPI
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/JimsApps/Snaz/SpotifyAPI.DLL
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Windows.Forms.resources
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_es_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------
AutoUpdater.NET
    Assembly Version: 1.2.0.0
    Win32 Version: 1.2.0.0
    CodeBase: file:///C:/JimsApps/Snaz/AutoUpdater.NET.DLL
----------------------------------------
System.Net.Http
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll
----------------------------------------
Newtonsoft.Json
    Assembly Version: 7.0.0.0
    Win32 Version: 7.0.1.18622
    CodeBase: file:///C:/JimsApps/Snaz/Newtonsoft.Json.DLL
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by JimmyAppelt** [comment]
Hi @hellnano can you do a check for me and see if SpotifyWebHelper.exe is running in the tasklist ?

**Comment by hellnano** [comment]
Hi, @Jimmy , yes, SpotifyWebHelper.exe is running in the tasklist.

The next/prev buttons are working but the pause/play buttons don't work in
snaz.

http://prntscr.com/8s27ch

**Comment by JimmyAppelt** [comment]
If u have skype, add me with `Jimmy Appelt` or `live:jim.appelt` thats probably easier to take a look at this problem. Also probably gonna need a peek on your system with teamviewer then.

**Comment by JimmyAppelt** [comment]
Are you running AVG antivirus ?

It seems that AVG Linkscanner is blocking communication between programs.

Let me know if this helped you :+1:

**Comment by JimmyAppelt** [comment]
Thanks for bringing this issue to my attention @hellnano 

After a closer look on the client machine we found that `AVG LinkScanner` blocks all communication between applications.

Possible solutions:

* Disable AVG LinkScanner
* Install a decent antivirus

If you are looking out to a better antivirus i recommend [Bit defender Total Security](http://www.bitdefender.com/solutions/total-security-multi-device.html?page=home)

**Comment by igamingpublic** [comment]
I don't know what's going on. I was using Spotify without a problem. it was working fine for a week. until the updated a day ago and the tab is now gone. Just because you cannot connected it means their server is down. I have no issues with spotify on snaz. I dont see any problems. Please bring back the spotify tab next update.

**Comment by hellnano** [comment]
@igamingpublic please read the changelog 
http://prntscr.com/8t4s7h

Hope @JimmyAppelt get a link for older version 1.10.0.7 to redownload asap.

**Comment by JimmyAppelt** [comment]
@igamingpublic @hellnano check #8. I posted an alternative link to 1.10.0.7 there

Always check the change log before you update :smile:

I know its painfull to see the tab is removed when it worked for you... but there are antivirus software's thats blocking the commiunication, for a server call reason.

Will try to get a fix out soon :+1:

**Comment by JimmyAppelt** [comment]
Almost have a new beta together with a full re-write of the playing now system.

The spotify feature is **completely** re-written, it will actually be called `Playing Now` instead of `Spotify (Playing Now)`

I made so that there can be more players added in the future. Spotify and foobar2000 will be implemented in the new beta.

**Comment by JimmyAppelt** [comment]
This feature is now re-written as of 1.11.1.0 with support for multiple players and the grab method is changed.

Enjoy !
