### ISSUE TITLE
About Chinese Translation

### ISSUE THREAD

**Issue by mattgam333** [JimmyAppelt/Snaz#70]
Hello JImmyAppelt,
I'd like to translate Snaz Into Chinese, Becasue many people in Taiwan Likes to use Snaz to help make their OBS Easier to use,
I use Snaz too, But I Think English is not simple to Taiwanese,
So I'd want to translate it,
If you see this, Please Reply me on Facebook
https://www.facebook.com/DEFY.TpWGodMatt
Or Github Or Email
*** (Email removed: do not write you're email on public areas)

Best Regards.

**Comment by JimmyAppelt** [comment]
Hi @mattgam333 

Thanks for you're support. But i will not make any translation available for snaz in the future.
