### ISSUE TITLE
Prevent the network traffic counter error or startup

### ISSUE THREAD

**Issue by thecold1** [JimmyAppelt/Snaz#71]
Hey there,

everytime I start Snaz I get 2 warning windows:

>Could not initialize the network traffic counter
>
>Cannot load Counter Name data because an invalid index " was read from the registry.

The window pops up twice. Is there a way to prevent Snaz from getting this error, I also don't use the feature so it's bugging me a bit.

Also If you need further information to fix the bug I'll let you have my system information etc.

**Comment by JimmyAppelt** [comment]
Hi @thecold1 

One ore more performance counters on you're machine are corrupted 9/10

Check here to fix that [https://github.com/JimmyAppelt/Snaz/wiki/Solving-warning-or-error-within-System-Info](url)

**Comment by thecold1** [comment]
Worked, just scrolled through open and closed issues, didn't saw the wiki, sorry!

Thanks for helping!
