### ISSUE TITLE
Spotify stops working completely after Ad (Playing Now)

### ISSUE THREAD

**Issue by JoelFardal** [JimmyAppelt/Snaz#72]
After an Ad plays on Spotify, it no longer shows media playing, the media playing changes to "No media playing" and when it gets to a new song it doesn't restart, it just stays completely empty.

**Comment by JoelFardal** [comment]
![is broke](https://cloud.githubusercontent.com/assets/19495839/15438521/d4fdfce4-1ecc-11e6-82ed-47d9d7f0fa34.png)

**Comment by JimmyAppelt** [comment]
Hi @JoelFardal,

I tested this today. I can't seem to replicate the issue you are having.

Do you always have this with specific songs ?

**Comment by JoelFardal** [comment]
It appears to be broken forever as no songs show up anymore, even with a restart.

**Comment by JoelFardal** [comment]
Oh it's fixed now, for whatever reason.

**Comment by JoelFardal** [comment]
NEVERMIND this is slightly glitchy

**Comment by JimmyAppelt** [comment]
If you have Discord, we can meet up ... so i can take a look with teamviewer on you're system :+1:

**Comment by JoelFardal** [comment]
I don't have Discord, Got teamspeak tho

**Comment by JoelFardal** [comment]
I can get Discord though.

**Comment by JimmyAppelt** [comment]
Sure, you can use it with the webbrowser to if you don't want to install it :+1:

**Comment by JoelFardal** [comment]
Aight it's installed

**Comment by JimmyAppelt** [comment]
Great, you can join and say hi :)

**Comment by JoelFardal** [comment]
What's the IP?

**Comment by JimmyAppelt** [comment]
Go to Snaz > Help menu > Discord ... this will bring you to the server

**Comment by JoelFardal** [comment]
gg

**Comment by JimmyAppelt** [comment]
After investigating the issue on the clients system, it appeared to have something to do with the `scroll` filter inside OBS.

*After playing with settings from the filter, expected behavior was reached again*
