### ISSUE TITLE
Chrono Up that allows 60+ minutes

### ISSUE THREAD

**Issue by TFletchuk** [JimmyAppelt/Snaz#73]
Great little program, but I'd like to use it as a Scoreboard with OBS Studio to stream Football (Soccer) matches.

The issue I have is that games last for 90 minutes and this is never shown on screen as 1hr 30mins but simply as a continuation of minutes, so I would like to be able to see 61mins+ rather than it resetting back to zero.

Is this possible?
Thanks

**Comment by JimmyAppelt** [comment]
Hi @TFletchuk 

This is currently not possible.

I wil leave this issue open as a request.

**Comment by TFletchuk** [comment]
Many thanks.

**Comment by JimmyAppelt** [comment]
Implemented as of 1.2.3.0 (Note: this implementation will work a bit different, at least for the time being)

Usage: `$totalminutes` and enable `Use custom format`

![804c79d673c39ebc20e07cf66e503279](https://cloud.githubusercontent.com/assets/5420393/17914473/bf62be76-69a2-11e6-867a-cff7fbfbdab1.png)

**Comment by JimmyAppelt** [comment]
Documentation can be found [here](https://github.com/JimmyAppelt/Snaz/wiki/Chrono-Up)
