### ISSUE TITLE
ChronoDown Bug

### ISSUE THREAD

**Issue by V3r1taz** [JimmyAppelt/Snaz#74]
Got a problem for some time now: Set it all up and it worked for a good amount of time but then (without changing a thing) the ChronoDown wouldn't show anymore, it would just display the end message the whole time.
After a reinstallation of SNAZ the problem got worse. Now it won't show neither of them.
The ChronoUp does work though. I tried it with XSplit and OBS to see if the problem lies with them but the issues stays the same with both.

**Comment by JimmyAppelt** [comment]
Hi @V3r1taz 

- What version of OBS do you use ?
- Does the text file itself update's on you're machine ?
- Are you using any filters (in OBS case) to enable scrolling or anything else ?

**Comment by V3r1taz** [comment]
I'm using OBS Classic 0.657b
The text files does NOT update itself it just stays empty since the problem started
Last but not least, no i don't use any filters. Neither have i in XSplit(and again i haven't changed any options in OBS or XSplit before the bug occured so it's pretty much the same as it was before)

**Comment by JimmyAppelt** [comment]
If Snaz is installed in a `Progam Files` directory ... then please try to install it in another folder, where no admin rights are necessary.

**Comment by JimmyAppelt** [comment]
@V3r1taz is your issue fixed ?

**Comment by JimmyAppelt** [comment]
Issue closed due no participation
