### ISSUE TITLE
SNAZ not updating various .txt files

### ISSUE THREAD

**Issue by GokouZWAR** [JimmyAppelt/Snaz#79]
I've seen this posted before, but others seem to be doing stuff that's not outlined in the files, or grabbing the wrong file for output in OBS. 

I've noted by opening the .txt files that snaz is not updating the file physically on my system at all. OBS is displaying the file accurately in my stream. Now snaz shows that the countdown, time, and viewer counts are updating in the application itself and showing accurately, but for some reason the application itself is not updating the physical file.

This was working fine before I installed new components including a new SSD which I am presently running on drive Z: Snaz and OBS have also been migrated to use the SSD on Z: and snaz was reinstalled and running on Z: as well. Is there some kind of limitation that snaz can only update to C:?

What things should I check for? Please note that irregardless of the version, snaz on the Z: is the same version as the snaz on C: which was operating perfectly before the hardware change as I used the same installation files. I did however do an update check on Saturday morning (June 18th, 2016) and it said no updates were needed so I can only assume its the latest version. As I'm not presently in front of my PC at home, I cannot provide the exact version readily.

**Comment by JimmyAppelt** [comment]
Hi @GokouZWAR ,

There is no limitation for installing on another drive ... snaz should work perfectly on all drives.

You mention that the snaz is unable to update the real textfile itself. The chance is high that for some reason snaz doesn't have proper rights to write or re-write the file.

I would follow the [https://github.com/JimmyAppelt/Snaz/wiki/How-to-perform-a-fresh-installation](https://github.com/JimmyAppelt/Snaz/wiki/How-to-perform-a-fresh-installation) guide.

The latest version of snaz is 1.12.2.1 [downloadpage](https://github.com/JimmyAppelt/Snaz/releases)

**Comment by GokouZWAR** [comment]
I ran snaz as administrator and that fixed the issue. Thanks
