### ISSUE TITLE
Window issue in 1.10.0.3

### ISSUE THREAD

**Issue by tibaland** [JimmyAppelt/Snaz#8]
Hello im using 1.10.0.3 because he work with spotify, i saw in changelogs 1.10.0.7 works too with spotify but when i try download, is download 1.10.0.8 without spotify.

You can give a link with 1.10.0.7 to download?

And the only way to work window again is reinstalling snaz i a diferrent fold 

example:  

C:\JimsApps\Snaz ( window not working ) 

C:\JimsApps\Snas ( window show again... )

**Comment by hellnano** [comment]
@tibaland hope @JimmyAppelt post an alternative download link for 1.10.0.7 asap.
check please the changelog o 1.10.0.5 http://prntscr.com/8t4thp (it's the same error and the solution is a total uninstall of snaz and reinstall)

**Comment by JimmyAppelt** [comment]
Hi @tibaland 

I pushed a few updates last few days indeed.

* I recommend you update to 1.10.0.8 and wait for next release if you have a problem with connecting to spotify.

* If you don't have a problem connecting you may find Snaz 1.10.0.7 [here](http://www.jimmyappelt.be/Downloads/Software/Snaz/Previous/SnazSetup1_10_0_7.exe) *(might be removed in the future)*

Please make sure to read changlog note from 1.10.0.5 like @hellnano mentioned :star2: as this is fairly important for future use:

> 1.10.0.5 note:
  If you installed Snaz previously inside a 
  C://Program Files/JimsApps folder please un-install and re-install again 
  (Not only update) To create all necessary permissions. This will fix all 
  issues regarding not updating files or not starting Snaz when in a 
  Program Files folder. My apologies for any inconvenience.

* Latest Snaz version can be downloaded [here](http://jimmyappelt.be/download/snaz)

In case there is a bug when Snaz does not open up (could be any reason at all). You can try
to remove all configuration files. **(Note that this will erase all settings inside snaz)**

You will find a folder called JimsApps inside `C:\Users\YOUR_USERNAME\AppData\Local`
 by removing this folder all settings will be removed/deleted from your system.

**Comment by JimmyAppelt** [comment]
A fresh installation involves 3 simple steps.

You can read the necessary steps to have a clean installation [here](https://github.com/JimmyAppelt/Snaz/wiki/Perform-a-fresh-install)

I will close this issue now. In case you still find that there is a problem feel free to reopen a issue.

**Comment by JimmyAppelt** [comment]
Is your problem solved with following the above steps @tibaland ?

**Comment by JimmyAppelt** [comment]
>As of 1.11.1.1 a re-install is not necessary anymore (just re-installing version 1.11.1.1 or above will fix this issue automatically)
