### ISSUE TITLE
Display Monstercat or Ninety9Lives songs 

### ISSUE THREAD

**Issue by Eldebras** [JimmyAppelt/Snaz#80]
Some streamers use Monstercat or Ninety9Lives streams on Twitch as music to their stream.
Why not make a option for that?

Both display in chat the song playing.
Read chat  and save the folowing in a textfile.

Something like:
Now Playing: New Beginning (feat. Kédo Rebelle) by Dustin Miles -> http://99l.tv/NewBeginningFM
or
Now Playing: Deya (Osmo Remix) [feat. Patrick Baker] by Televisor, Patrick Baker - Listen now: http://spoti.fi/1Xr8Ap4

**Comment by JimmyAppelt** [comment]
Hi @Eldebras,

At this moment Snaz does not connect with Twitch IRC at any time ... this would be an extensive 
feature as IRC has to be integrated.

For such extensive features i have to have support from multiple users.

**Comment by Eldebras** [comment]
Ok then i understand. Thank you for the info.




Den 2016-06-24 kl. 12:53, skrev Jim:
