### ISSUE TITLE
Add VLC Player to Playing Now

### ISSUE THREAD

**Issue by User93814** [JimmyAppelt/Snaz#84]
Another popular video player that plays Video and Audio files.

Link: http://www.videolan.org/vlc/

**Comment by JimmyAppelt** [comment]
@User93814 thanks for you're request :+1:

**Comment by JimmyAppelt** [comment]
Will be available from 1.2.3.0 once released out of beta

**Comment by JimmyAppelt** [comment]
Docs: [https://github.com/JimmyAppelt/Snaz/wiki/VLC-media-player](https://github.com/JimmyAppelt/Snaz/wiki/VLC-media-player)

**Comment by JimmyAppelt** [comment]
hi @User93814,

Would you be willing to beta test VLC media player, Sir ?

**Comment by User93814** [comment]
Hello @JimmyAppelt,

Yes, most certainly will be able to do that for you. I'll give you some feedback within the next 48hours.

**Comment by JimmyAppelt** [comment]
@User93814 

The beta's are downloadable trough our discord server. I will need you're login name to *(since only beta testers get access)*

You can login into the discord trough the `Help> Discord Chat` menu
