### ISSUE TITLE
Timer goes off by a minute each hour

### ISSUE THREAD

**Issue by kddove85** [JimmyAppelt/Snaz#87]
I tested out your product today with a 12 hour stream on Twitch. I want to say I'm very satisfied with your product. However, it appeared that by the end of the 12 hour stream, the timer was off by about 12 minutes. If you like, I will send you a link to the stream as support.

**Comment by JimmyAppelt** [comment]
Hi @kddove85 

I can see the time difference on you're recording. Although i have no idea why ...

I tested the up-time timer last 10 hours, *just for you* ... it was correct on the second.

**Comment by kddove85** [comment]
Thank you for looking into this Jimmy. I can't say for sure why the timer was off either. I've only used the product for two days now. I'll try another stream with maybe multiple count ups and see if they get out of sync. Thank you again.

**Comment by JimmyAppelt** [comment]
No problem, if in any case you find something weird ... you are welcome to re-open the ticket or open a new one :+1:
