### ISSUE TITLE
"Death Counter" mechanic

### ISSUE THREAD

**Issue by joXnka** [JimmyAppelt/Snaz#88]
It would be great if Snaz was able to generate a file that would simply keep count of deaths. 
File would just count from "0" adding +1 to the number every time the streamer dies.
The streamer would inform Snaz he just died by pressing a keyboard combination (of our choice?)
That way we could have a "Times [Streamer] Died: X" (where X would be the number form the file)
There should obviously be a button for resetting and manually setting it to a value.
Thanks!

**Comment by JimmyAppelt** [comment]
Hi @joXnka 

This seams to be a duplicate request #32 :wink:
