### ISSUE TITLE
Disable "running minimized" notification

### ISSUE THREAD

**Issue by GibStorm** [JimmyAppelt/Snaz#89]
Please make an option for not triggering the "running minimized" notification every time the application starts/is minimized.

**Comment by JimmyAppelt** [comment]
Hi @GibStorm,

In windows you can disable/enable notifications in the notification center itself

**Comment by GibStorm** [comment]
Haha yes, but sadly that doesn't work. Never has.

**Comment by JimmyAppelt** [comment]
Ok i know it is sometimes faulty, the windows actions center.

In the meantime you can go to Snaz settings and enable `Keep snaz on the taskbar`

**Comment by JimmyAppelt** [comment]
An option in `File>Settings>On minimize` - `Hide notification` available from 1.2.3.0
