### ISSUE TITLE
More countdowns and/or more ChronoDowns/Ups 

### ISSUE THREAD

**Issue by thecold1** [JimmyAppelt/Snaz#90]
I already use ChronoDown and normal countdown to display the time when the stream will start and when the break is over. If I ever need another countdown I have to rename them and rename them back to their defaults after the stream.

How about some more "tabs" with more countdowns and/or ChronoDowns/ChronoUps?

**Comment by JimmyAppelt** [comment]
hi @thecold1 ,

I currenlty have no plans to add more tabs with more countdowns or chrono's. IN case you want another one, the way you can do it is to run Snaz twice.

For this to work you have to copy everything in a new folder *e.g. Snaz2* and rename the following two files also :

![20600f65ec4e318c65581023a3a00480](https://cloud.githubusercontent.com/assets/5420393/16959440/6ac18e66-4de5-11e6-9d0e-9d42103d5430.png)

to: 

- Snaz2.exe
- Snaz2.exe.config
