### ISSUE TITLE
Now Playing shows album and art not in ID tag. 

### ISSUE THREAD

**Issue by RyogaVee** [JimmyAppelt/Snaz#91]
Have no idea how this is happening. 
I'm using winamp for displaying album art and song. 
However all my "Tool" tracks are listed having the album "**Electro-Acoustic Tribute To Tool, The**" and the corresponding album art. Song titles are correct though. 

The album art and title is from an album I have never owned or ever downloaded. I have manually changed the album art and album titles for all my Tool tracks. But there seems to be no remedy. 
This is happening to ALL my tool tracks regardless of album. 

However when I use the Snip app, it plays correctly. 

Where is Snaz getting this album and art data from if its not in the ID3 tags?
Attached is an image showing itunes, winamp ID3 tags and the image of what is displayed in OBS. 

![snaz fw](https://cloud.githubusercontent.com/assets/4732393/17196738/a10b971e-541b-11e6-88ab-512b6d842a8a.png)

**Comment by JimmyAppelt** [comment]
The behavior of the album name and art is absolutely normal, this is because the information is not pulled from Winamp or ID3 tag.

The information is pulled from a online database owned by spotify (the largest database available) ... the album name and art is the first queried from the database.

**Comment by RyogaVee** [comment]
So, for titles that dont have database matches, they are pulled form the ID# 2nd?

**Comment by JimmyAppelt** [comment]
Ah ... no ... snaz will only query the database if there is no result, then you have no album or albumart.

**Comment by RyogaVee** [comment]
last question: In this case. Snaz is querying the database even though there is album art and tag info. 
What info is missing to make it think there is no match?

**Comment by JimmyAppelt** [comment]
The query is build to make a request with the `Artist` and `Songname` ... so these needs be correct and need to exist in the spotify database.

**Comment by JimmyAppelt** [comment]
As of 1.12.3.0 iTunes is implemented - with this player you can retrieve the exact album and album art that is presented in the player itself. [https://github.com/JimmyAppelt/Snaz/wiki/iTunes](https://github.com/JimmyAppelt/Snaz/wiki/iTunes)
