### ISSUE TITLE
Snaz for IOS 

### ISSUE THREAD

**Issue by BaileyMcE** [JimmyAppelt/Snaz#92]
Hey, I'm looking to get a countdown feature for my stream, but I cant find a method that works for mac. Just wanted to know if there was a way that I dont know of that would work or if Snaz has plans for the future that would allow mac users to use the application.

Thanks.

**Comment by JimmyAppelt** [comment]
Hi @BaileyMcE ,

You could try out Wine [https://www.winehq.org/](https://www.winehq.org/)
