### ISSUE TITLE
Winamp Now Playing not retrieving correct data

### ISSUE THREAD

**Issue by Marscaleb** [JimmyAppelt/Snaz#93]
I have the "playing now" set to use winamp, and the track info it retrieves is incorrect.  It seems to be assuming a default title formatting, but I have made changes to the title formatting Winamp uses.  As such, my alum info appears in Snaz as the artist info, and my artist and song info appear as just the song info.
While the current functionality is acceptable, I can't extend the functionality nor customize it any further.  I can make formatting changes within Winamp, but I can't make formatting changes within Snaz, and as such Snaz is only capable of outputting a direct copy of what I have Winamp outputting.

Furthermore, I seem utterly incapable of retrieving album images from Winamp, and if I have Winamp set to scroll the track info in the taskbar, Snaz becomes incapable of correctly reading the title info.

It seems to me that Snaz is simply reading the text Winamp displays in the taskbar and making assumptions about what that information means.
Granted, if Snaz were trying to read the data from the file Winamp is trying to play, it would run into problems with the special formats I run through winamp plug-ins.
But I would be willing to install a special plugin into Winamp to have it properly interact with Snaz and have Snaz identify and display the correct data.  Just sayin'.

**Comment by JimmyAppelt** [comment]
Hi @Marscaleb 

The song and artist are captured trough window hook capturing (the title of the window). The title formatting needs to be the default one `[%artist% - ]$if2(%title%,$filepart(%filename%))`.

The artist and album name are searched on a online database and is a random album that contains the song (if exist in the database).

**Comment by RyogaVee** [comment]
Can I suggest that if the user is playing the file locally it should NOT retrieve any info from the database.
A large majority of my music is NOT on spotify. and thus cant be displayed as intended in snaz.

**Comment by Marscaleb** [comment]
Exactly what  RyogaVee said.  I don't need it to pull information from an online database; I have all the information locally in the file itself.  I would just like Snaz to properly identify what attributes are what in a given track name, so when I have Snaz output that data to a file I can add my own custom formatting.  (For example, swap the hyphen between segments for a line break.)

This could be resolved as simply as allowing me to tell Snaz what formatting I am using within winamp, For example instead of the default format, I use `[%album% - ][%artist% - ]$if2(%title%,$filepart(%filename%))` which will display album titles as well as artist and title.  Snaz could then read the title of the window and decode the filename further to identify elements more correctly.

Of course, it still leaves room for error, (in the above example, if a track has only artist or only album info, there is no way to identify which is being displayed,) which is why I suggested possibly using a plugin for winamp that would send Snaz the track info directly.  It could also send snaz the physical address of the file in question, and thus Snaz could try to to read the file for album art, then if not found check the directory for album art, and then if not found could check online for album art as per normal.
Such a feature would also allow me to scroll the title in the taskbar, which I like to do.

**Comment by JimmyAppelt** [comment]
@RyogaVee as the module is coded for multiple music players, there is no such option to implement for only winamp i'm afraid.

@Marscaleb the only thing i would be able to implement regarding this issue is the option to read the whole title and display it. Decoding a personal formatting for each person is a no go as there is a algorithm in place to do so.
