### ISSUE TITLE
Pause for Chrono Up

### ISSUE THREAD

**Issue by Ragowit** [JimmyAppelt/Snaz#94]
I want to be able to pause the Chrono Up. Now I need to hit "Stop" and that makes the timer to be an empty string until I start it again.

**Comment by JimmyAppelt** [comment]
hi @Ragowit 

Indeed the stop button actually pauzes and will make the string empty. You would like to show the string as it is pauzed/stopped ?

**Comment by Ragowit** [comment]
That is correct.

I use the timer when I play a game to show my viewers for how long I have been playing the game I currently stream. Sometimes I need to take short breaks (fetching a glass of water, answer the phone, etc), which makes me want to pause the timer. Currently, this makes the timer completely disappear. I still want the timer to be showed, just paused.

**Comment by JimmyAppelt** [comment]
I will mark this one as a request then :+1:

**Comment by SilentLilac** [comment]
REALLY REALLY Want this feature!!! Would mean I won't have to look for another program just to do that!!

**Comment by JimmyAppelt** [comment]
Pause for chrono up will integrated  in 1.12.5.1
