### ISSUE TITLE
Countdown When done msg not showing up

### ISSUE THREAD

**Issue by WSP-webmaster** [JimmyAppelt/Snaz#95]
Running Snax 1.12.2.1 - Win 7 SP1 64bit

When countdown timer should stop both sound and Msg when done do not trigger

**Comment by JimmyAppelt** [comment]
Its running fine on my system, i'm running Win 10 64-bit. 
I'm unable to test Snaz on a Win 7 system. Perhaps you have a buddy to test it on the same specs ?

**Comment by WSP-webmaster** [comment]
The Chrono's down are running fine but the Countdown to specific time doesn't seem to want to update the life output

**Comment by JimmyAppelt** [comment]
Could you try and run snaz as admin ?

**Comment by WSP-webmaster** [comment]
Testing that out now

**Comment by WSP-webmaster** [comment]
This is screen cap on NON admin test
https://db.tt/c2PCVWoo

**Comment by WSP-webmaster** [comment]
running in admin did not seem to make a difference in live output

**Comment by JimmyAppelt** [comment]
Please upload screenshots by pasting/upload the image here directly. Pressing unknown links is never  save ;)

**Comment by WSP-webmaster** [comment]
Thats to my dropbox but I understand. One moment please

**Comment by WSP-webmaster** [comment]
![timer running](https://cloud.githubusercontent.com/assets/7007298/17563948/a32a530c-5eff-11e6-8410-a0f402314af5.jpg)
![no msg pop after countdown end](https://cloud.githubusercontent.com/assets/7007298/17563947/a32a2c92-5eff-11e6-8e72-2065e6a16f03.jpg)

**Comment by WSP-webmaster** [comment]
![chrono work fine](https://cloud.githubusercontent.com/assets/7007298/17564017/e3fe7f0c-5eff-11e6-9aab-b1868802c9f4.jpg)

**Comment by WSP-webmaster** [comment]
You can close this thread. Solution found! By pressing the "set date and time to current system values" it worked
