### ISSUE TITLE
Chrono down end ---> Chrono Up start

### ISSUE THREAD

**Issue by MrAtlantis646** [JimmyAppelt/Snaz#97]
I would like to have the feature when the Chrono Down has ended the chrono up starts automatically.

I hope this is possible,

MrAtlantis646

**Comment by JimmyAppelt** [comment]
Will be available from release 1.2.3.0

(in the Chrono Up module will be a setting `Auto start when Chrono Down ends`

![686b197ba99a056542f910b389869ec6](https://cloud.githubusercontent.com/assets/5420393/17916196/598e4796-69b1-11e6-93bc-36375c881b69.png)
