### ISSUE TITLE
[Suggestion] Multiple shortcuts for countdown to increase time

### ISSUE THREAD

**Issue by kcmartz** [JimmyAppelt/Snaz#99]
A streamer I watch uses the countdown, and then when X event happens, adds more time to the counter (for the stream end time). I'd love a way to add time to it via a keyboard shortcut. Maybe in increments of like 1 minute, 5 minutes, 10 minutes, or make it customizable?

If you need more info, let me know!

**Comment by jcolsen** [comment]
This has been asked a lot, adding my vote.

**Comment by kcmartz** [comment]
Oops I found it the other guys use countdown not Chrono down. Typo!!

**Comment by JimmyAppelt** [comment]
@kcmartz you always can "Edit" your title and post .. no problem.

**Comment by kcmartz** [comment]
Not on mobile afaik ;)

**Comment by BDRMrTBag** [comment]
I'd definitely vote for this feature! I've looked all over for one and I can't find any that I can use, hopefully you decide to add it! :D
